### ISSUE TITLE
`target add` and `component add` should succeed if target/component is already installed

### ISSUE THREAD

**Issue by brson** [rust-lang/rustup#1009]
For automation purposes it's nice for this command to 'just work' when these commands are done redundantly. Change these commands to issue an 'info' indicating the thing is already installed and return successfully.

**Comment by typesanitizer** [comment]
For cases when the target is distinct from the toolchain (say target=`x86_64-pc-windows-gnu` and toolchain=`stable-x86_64-unknown-linux-gnu`), there is an `info` issued along the lines of:

```
 info: component 'rust-std' for target 'x86_64-pc-windows-gnu' is up to date
```
Call order for issuing this info: [`bare_add_component`](https://github.com/rust-lang-nursery/rustup.rs/blob/a1287b6e897e495fb8371a2dfebf2e5f41d4365b/src/rustup/toolchain.rs#L547) -> ??? -> [`update`](https://github.com/rust-lang-nursery/rustup.rs/blob/a1287b6e897e495fb8371a2dfebf2e5f41d4365b/src/rustup-dist/src/manifestation.rs#L452) -> ??? -> `fmt` (in `notifications.rs`) which calls  [`ComponentAlreadyInstalled`](https://github.com/rust-lang-nursery/rustup.rs/blob/a1287b6e897e495fb8371a2dfebf2e5f41d4365b/src/rustup-dist/src/notifications.rs#L75).

The error only happens when the target is a part of the toolchain (say target=`x86_64-unknown-linux-gnu` and toolchain=`stable-x86_64-unknown-linux-gnu`). I think this error is coming from [here](https://github.com/rust-lang-nursery/rustup.rs/blob/a1287b6e897e495fb8371a2dfebf2e5f41d4365b/src/rustup/toolchain.rs#L567).

1. Should this error be matched and an `info` be issued in the corresponding functions `target_add` and `component_add` in [`rustup_mode.rs`](https://github.com/rust-lang-nursery/rustup.rs/blob/f9077d2fae3882e4fb45d8a35ee241911a3b4fee/src/rustup-cli/rustup_mode.rs)?
2. Should the `info` be issued using the same notification mechanism or do you just use a simple `info!` macro in the definitions for `target_add`/`component_add`?

**Comment by nre-ableton** [comment]
I'm also running into this "error" and find it very confusing. I am not sure why `rustup` would fail in this case when everything is in an "ok" state. Are there any plans to fix this?

**Comment by kinnison** [comment]
I believe this is now the case, if it's not, please open a fresh issue detailing what failed and what you'd expect.
