### ISSUE TITLE
Warn when using an old nightly without an override

### ISSUE THREAD

**Issue by boustrophedon** [rust-lang/rustup#1106]
I was under the impression for some reason that "nightly" was somehow automatically updated when you tried to use it, eg. in `rustup run nightly cargo install clippy`, and wasted a bunch of peoples' time on IRC.

It would be nice if rustup warned you that you're on an old nightly and you haven't set an override.

I'd be willing to work on this if someone can give me pointers on where to look and what to change.

**Comment by boustrophedon** [comment]
@rkruppe is also raising the usecase where you deliberately don't run `rustup update` for a period of time due to regressions in nightly, instead of pinning with `override`.

**Comment by Diggsey** [comment]
I think we wouldn't want to warn on every use, because people expect the proxies to behave like their original counterparts, which means not altering their output in any way.

Maybe there could be some visual indication in `rustup show` though that a toolchain is out of date? I don't think it's a high priority right now though, without a stronger motivation.

**Comment by kinnison** [comment]
We have `rustup check` which will check for updates to installed toolchains and report what toolchains would try and update if you were to run `rustup update`.  If this is sufficient to resolve the OP's issue given our reluctance to attempt an update on every use, then please close.

**Comment by boustrophedon** [comment]
I don't really see this as a problem anymore tbh. Having `rustup check` is probably good enough. Closing the issue.
