### ISSUE TITLE
Installation of Visual Studio tools is not well integrated

### ISSUE THREAD

**Issue by kornelski** [rust-lang/rustup#1114]
When installing Rust on Windows for the first time there's a wall of text, including a message saying that Visual Studio tools needs to be installed.

* Wall of text is not a nice experience, and if you don't read it, you get worse setup.
* It's a completely manual step. 
* Copying of the URL from console is a bit cumbersome.

I'd prefer if Rustup had an option to at least automatically open the VS download URL. It could be the first option when user presses Enter, so user would be guided towards best solution even if they don't read the instructions.

If #253 is integrated, it'd be nice if VS install was a step in the installer.

**Comment by ctaggart** [comment]
The current installer prints this:

![image](https://user-images.githubusercontent.com/80104/42729254-eb136f16-8796-11e8-89fd-6bd81bcebb36.png)

In my case, I have Visual Studio 2017 already installed. It would be nice if `rust-init.exe` launched or made it easy to launch a script that installed the required dependencies.

**Comment by rami3l** [comment]
It seems to me that this has been fixed.

As described in https://github.com/rust-lang/rustup/blob/81a71647f4615d85267325b8dd8019a37e01f9fd/doc/user-guide/src/installation/windows-msvc.md, Rustup will now offer to install VS C++ build tools automatically (since #2954).

Also, the page above provides a rather detailed list of steps to follow if you'd like to install these tools manually.

Please feel free to reopen if you believe that is not the case.
