### ISSUE TITLE
Create and publish a snap of rustup

### ISSUE THREAD

**Issue by flexiondotorg** [rust-lang/rustup#1144]
I work on the team developing Ubuntu and [Snapcraft](https://snapcraft.io) and recently spoke to @brson  and @alexcrichton about creating and publishing a snap of rustup. They requested that we raise an issue here for creating a snap so that it can be included as a call for participation in a future [This Week in Rust](https://this-week-in-rust.org/) news letter.

For those unfamiliar with snaps and snapcraft, you can get a quick introduction from our video [Snaps and snapcraft.io explained in 3 minutes](https://www.youtube.com/watch?v=DLxqdf89hRo).

As requested an issue to snap Rust has also been filed:

  * https://github.com/rust-lang/rust/issues/42349

**Comment by est31** [comment]
cc #800

**Comment by brson** [comment]
I kinda think getting nice rustup snaps is probably even more desirable than plain [rust](https://github.com/rust-lang/rust/issues/42349#issuecomment-305933888) snaps, since rustup provides the full Rust experience. I can imagine the official Rust snap actually being rustup - you go to the nice Linux app store, search for Rust in the typical way, and you get the works.

Deploying official rustup snaps is potentially easier than official Rust snaps because rustup releases are not tied to the massive Rust CI beast, where deploying snaps would require a number of integrations. It's easier to experiment outside of the rust-lang/rust tree.

Snapping rustup though is going to have significant challenges compared to snapping a single Rust toolchain:

- rustup is installed at the user level, not at the system level. I understand snap is capable of doing this kind of thing, but it's surely going to be less straightforward than just touching /usr/local.
- rustup has an integrated self-updater that should not be used when packaged by other systems.

Getting started here will probably just take a bunch of exploratory work to see how plausible it is to make a rustup snap work correctly with the `~/.rustup` and `~/.cargo` directories.

**Comment by brson** [comment]
I posted this to [TWiR](https://users.rust-lang.org/t/twir-call-for-participation/4821/61).

**Comment by lilianmoraru** [comment]
I actually don't like that some distros distribute Rust without `rustup`... It is a critical component of the Rust ecosystem and experience. To me seems more important to distribute `rustup`, than Rust itself.
I am not sure though how well will `rustup` work inside a `snap`, especially considering that it uses the user's home directory.

**Comment by kinnison** [comment]
Rustup snaps have been out (and quite popular) for some time now.

**Comment by est31** [comment]
Link: https://snapcraft.io/rustup
