### ISSUE TITLE
Feature request: Set PATH on Windows when spawning via `rustup run`

### ISSUE THREAD

**Issue by olson-dan** [rust-lang/rustup#1152]
See here: https://github.com/Manishearth/rust-clippy/issues/1815

`rustup run` could resolve the issue clippy has with needing the PATH set by appending (or prepending?) the requested toolchain's bin folder to PATH before spawning the process.  This would make it easier to maintain multiple toolchains without shuffling different PATH configurations.

**Comment by Diggsey** [comment]
You can't `cargo install` clippy and have it work with multiple toolchains - the problem is that clippy links against the compiler DLLs, and those need to match the toolchain with which clippy itself was compiled, *not* the toolchain that is currently in use.

There are two solutions, either clippy needs to be distributed as a toolchain component, so that you install clippy once per toolchain, and it automatically has access to the compiler DLLs, or clippy needs to copy the compiler DLLs on which it depends into the output directory as part of the build/installation step.

Dup. of #876 #765 #350 etc. etc.

**Comment by oli-obk** [comment]
That's not quite true. Clippy needs to be run with the toolchain it was built with. But yea, in the long run there'll be another solution on the clippy end
