### ISSUE TITLE
`rustup update nightly` fails with `missing key: 'url'`.

### ISSUE THREAD

**Issue by alex-ozdemir** [rust-lang/rustup#1174]
```
$ rustup update nightly
info: syncing channel updates for 'nightly-x86_64-unknown-linux-gnu'
error: missing key: 'url'
```

Version:
```
$ rustup --version
rustup 1.4.0 (a77fbedf2 2017-06-09)
```

Unsure if the underlying cause is related to #1062.

**Comment by alex-ozdemir** [comment]
Welp, this seems fixed for me. I'm unsure why. The interesting sequence of events:

```
$ rustup update nightly
error: missing key: 'url'
$ rustup --version
  // something old

$ rustup self update
$ rustup --version
rustup 1.4.0 (a77fbedf2 2017-06-09)
$ rustup update nightly
info: syncing channel updates for 'nightly-x86_64-unknown-linux-gnu'
error: missing key: 'url'
// Welp. I file the issue

$ rustup install nightly-2017-06-18
$ rustup default nightly-2017-06-18
// Working on things
// ...
// Even *that* version of the compiler becomes too old for this particular work
$ rustup update nightly
// Correctly updates.
// Wat?
```

I'll leave the issue open here so that relevant people see it.

**Comment by Diggsey** [comment]
Fixed in #1063

**Comment by shepmaster** [comment]
This [happened last night again](https://travis-ci.org/integer32llc/rust-playground/jobs/255088861) (and seems to still be the case today) for beta:

```
Step 10/15 : RUN rustup default "${channel}-${date}"
 ---> Running in 075281f84d5b
info: syncing channel updates for 'beta-2017-07-18-x86_64-unknown-linux-gnu'
error: missing key: 'url'
The command '/bin/sh -c rustup default "${channel}-${date}"' returned a non-zero code: 1
```

/cc @erickt

**Comment by CryZe** [comment]
@shepmaster It's because Travis CI's rustup is still on 1.4.0

Does anyone know where this is in Travis CI's repositories?

**Comment by shepmaster** [comment]
@CryZe haha, you answered my question, but for the wrong reason 😉 

I don't use Travis' rustup, but I bet my Docker containers have an old version of rustup installed. I install rustup with just a `curl` command, which Docker can't tell needs to be updated over time. I avoid the similar problem with Rust proper because I download a manifest file and grab the latest stable/beta/nightly dates for that and parameterize the Docker build using them, which busts the cache.

I'll have to look to see if rustup has something similar I can use.

Thanks!
