### ISSUE TITLE
 error: toolchain 'nightly-x86_64-pc-windows-msvc' does not support components

### ISSUE THREAD

**Issue by GrahamBest** [rust-lang/rustup#1184]
Hey, running
`D:\Rust Fixed\testdll>rustup target add i686-pc-windows-msvc `
gives me the error
`error: toolchain 'nightly-x86_64-pc-windows-msvc' does not support components`
I have an x64 system. Trying to build a 32 bit DLL. Anyone here have any experience with this?

**Comment by Diggsey** [comment]
What is the output of running `rustc --version` in that directory?

It could be that you have a very *very* old nightly, from before components were added. If that's the case, you just need to run `rustup update` and then try again.

**Comment by GrahamBest** [comment]
@Diggsey 
rustc 1.18.0 (03fc9d622 2017-06-06)

Thats whats outputted. I'lll try rustup update and report my results.

**Comment by Diggsey** [comment]
@Verideth That's not right - that version is a stable rust version, but the error you posted previously shows that you're installing the target for a nightly version of rust.

**Comment by GrahamBest** [comment]
@Diggsey Yes, I want to use a nightly version of rust. Anyway to fix this?

**Comment by Diggsey** [comment]
@Verideth Please run these commands in that same directory:
```
where rustc
where rustup
rustup show
rustc --print sysroot
```

And post the result.

**Comment by GrahamBest** [comment]
```
D:\Rust Fixed\testdll>where rustc
C:\Program Files\Rust stable GNU 1.18\bin\rustc.exe
C:\Users\gecko\.cargo\bin\rustc.exe

D:\Rust Fixed\testdll>
D:\Rust Fixed\testdll>where rustup
C:\Users\gecko\.cargo\bin\rustup.exe

D:\Rust Fixed\testdll>
D:\Rust Fixed\testdll>where rustup
C:\Users\gecko\.cargo\bin\rustup.exe

D:\Rust Fixed\testdll>
D:\Rust Fixed\testdll>where rustup
C:\Users\gecko\.cargo\bin\rustup.exe
```

**Comment by GrahamBest** [comment]
Those are my results

**Comment by Diggsey** [comment]
Uh, you ran `where rustup` three times 😛 . No matter - the problem is that you've installed rust via the installer, and that's the version of rust that's on your PATH first, so rustup is not being used.

If you're using rustup, you don't need to install rust separately. Remove `C:\Program Files\Rust stable GNU 1.18\bin\` from your PATH environment variable, and uninstall it if you don't need it anymore.

Once you've done that, run `rustc --version`. Previously this would have been very old (hence the error about components) but now that you've done a `rustup update` is should be a recent version, and you should be able to manage targets successfully.

**Comment by GrahamBest** [comment]
Well @Diggsey I thank you a ton!!!

It worked _somewhat_, it changed rustc to nightly. However I'm still having the same problem. I don't know whats going on! But here take this as a reward :) 🥇 

I'll report back if I get it to work

**Comment by Zbyl** [comment]
I had the same problem.
It worked when I manually installed RLS using Setup instructions from:
https://github.com/rust-lang-nursery/rls

**Comment by kinnison** [comment]
If you're encountering similar errors with a modern rustup, please open a fresh issue.  I'm closing this one as it hasn't seen movement in over two years.
