### ISSUE TITLE
Wrapper complains `stable-i686-pc-windows-gnu` isn't installed even though `stable-x86_64-pc-windows-msvc` is

### ISSUE THREAD

**Issue by Arnavion** [rust-lang/rustup#1333]
```ps
$ rustup toolchain list

stable-x86_64-pc-windows-msvc

$ rustc +stable -vV

error: toolchain 'stable-i686-pc-windows-gnu' is not installed
```

And, possibly related to #1332:

```ps
$ rustc +stable-msvc -vV

error: toolchain 'stable-i686-pc-windows-msvc' is not installed
```

**Comment by Diggsey** [comment]
This is the expected behaviour if your `Default Host` is set to `i686-pc-windows-gnu`

You can see this on the first line of output from `rustup show`.

You can change your default host with `rustup set default-host`. However, if your host really is 32-bit, you will not be able to use 64-bit toolchains, even though you can install them.

**Comment by Arnavion** [comment]
Yes, I did notice that it stopped being a search of installed toolchains and started being determined based on the default-host setting (this change is probably why the readme is also inconsistent, as in #1332 ).

Now I'm not sure *why* the default-host for Windows is set to i686 when Linux does default to x86_64... I assume because 32-bit Windows is popular enough that you want rustup users to be able to target 32-bit Windows by default even if they themselves are on 64-bit Windows?

**Comment by Diggsey** [comment]
The behaviour hasn't changed here: it's always been based off the host target, and has never searched installed toolchains.

The readme is likely inconsistent because it was written assuming a 64-bit host, and the way in which the "default host" was selected has changed to now prefer 32-bit. (Although it will remember your previous selection)

I believe the rationale for this change is that both toolchains can target both 32-bit and 64-bit windows via `rustup target add`, and so it makes most sense to install a 32-bit version of rustc, since that will run anywhere.

**Comment by Arnavion** [comment]
>and the way in which the "default host" was selected has changed to now prefer 32-bit.

Ah, that would make sense. I guess I misatttributed the original behavior to searching based on the toolchain names. Thanks.
