### ISSUE TITLE
Show more useful information when user input a short version of toolchain

### ISSUE THREAD

**Issue by upsuper** [rust-lang/rustup#1407]
I tried to install Rust 1.24 via rustup, but when I type
```
rustup toolchain install 1.24
```
it reports
> error: toolchain '1.24' is not installed

It took me quite a while to figure out what's wrong with the version, but eventually I realized that it is because rustup expects the whole three-part version number. With `1.24.1` I successfully installed the toolchain I wanted.

But I think the error message here can definitely be improved, for example, maybe "error: toolchain '1.24' doesn't exist. Maybe you mean '1.24.0'". Or probably rustup should just handle this case transparently for users so that people don't need to type the whole version.

**Comment by kinnison** [comment]
Currently the error you get is:

> error: invalid toolchain name: '1.24'

I'm not sure I'd want us to "guess" the user meant `1.24.0` or even to start fetching channel manifests from 0.. until we find the latest patch for a given release because that's a lot of assumed work.

If I said `rustup toolchain install 1.xx` and it installed 1.xx.0, should it have created the toolchain `1.xx.0` or should it be called `1.xx` still -- if it's the latter, would a later `rustup update` be expected to see if `1.xx.1` is available?

All in all I think this should be closed - the error message is now good enough and the behaviours suggested are problematic in terms of expectation meeting.

@upsuper if you a good idea of a workup for unsurprising (intuitive) UX for this, please open a fresh issue detailing it as an enhancement request.

**Comment by upsuper** [comment]
I think a good start would be just say "maybe you mean 1.24.0", it would at least reassure user that it does indeed support installing a specific version, rather than leaving them doubt their impression.

The error message still seems to be just
> error: invalid toolchain name: '1.24'

which I don't think it can be said "good enough". It's like rustc telling user that there is an error in their code without telling them where it is.

**Comment by upsuper** [comment]
> @upsuper if you a good idea of a workup for unsurprising (intuitive) UX for this, please open a fresh issue detailing it as an enhancement request.

I think I have made several suggestions in this post, and don't think it makes sense to open a new one for mostly the same issue. If you insist that this is not a problem, I'm not going to argue.

**Comment by kinnison** [comment]
Your point that it doesn't help the user is well received.  I will see if I can improve matters a bit...

**Comment by kinnison** [comment]
@upsuper It'd be super-handy if you could look at the examples on #2117 and tell me if that'd be good enough

**Comment by upsuper** [comment]
Thanks for the PR.

I didn't think about even checking the named channels, but it indeed makes sense. The suggestion for `x.y.0` should be good enough to inform user what to try, although I guess the wording could probably be bikeshedded a bit.

**Comment by kinnison** [comment]
I want to avoid bikesheds until someone actively complains :D  I'll take that as an approval assuming the CI passes, thank you.
