### ISSUE TITLE
Instal rust with msys2.exe doesn't install gnu version

### ISSUE THREAD

**Issue by TLmaK0** [rust-lang/rustup#1409]
I have tried to install windows gnu version from msys2. By default tries to install windows-msvc, if you change to ```x86_64-pc-windows-gnu``` it installs msvc also.

With rustup works as expected.

With msvc version cargo fails when compiles ```winapi```.

**Comment by Diggsey** [comment]
Can you clarify what exactly the issue is here?

You said "With rustup works as expected."

Installing `-msvc` by default is the expected behaviour, but you should be able to change this during installation - is that part not working for you?

Please describe exactly what steps you took, and how the behaviour differed from what you expected.

**Comment by rbtcollins** [comment]
I'm closing this as the bug is not clear enough to act on and the original reporter hasn't responded to the request to clarify.
