### ISSUE TITLE
it won't upgrade on FreeBsd 11

### ISSUE THREAD

**Issue by GildedHonour** [rust-lang/rustup#1440]
On FreeBsd 11:

```
$ rustup update
info: syncing channel updates for 'stable-x86_64-unknown-freebsd'
info: latest update on 2018-06-05, rust version 1.26.2 (594fb253c 2018-06-01)
error: component 'rust-docs' for 'x86_64-unknown-freebsd' is unavailable for download
info: checking for self-updates

  stable-x86_64-unknown-freebsd update failed - rustc 1.25.0 (84203cac6 2018-03-25)

```

**Comment by Diggsey** [comment]
This is the correct behaviour for rustup so that you don't just "lose" components when you upgrade. The fact that the rust-docs component was not built for a tier 2 platform looks like a bug which you should report [here](https://github.com/rust-lang/rust) assuming there's not already an issue about it.

**Comment by GildedHonour** [comment]
what's  tier 2 platform?
