### ISSUE TITLE
Not all toolchains contain all targets

### ISSUE THREAD

**Issue by glandium** [rust-lang/rustup#1473]
I was looking at my disk space usage, and the rustup directory was showing prominently, so I took a dive in the directory and noticed something weird: I have stable, beta and nightly toolchains installed, and 5 different targets (android-arm, windows, darwin, linux x86-64 and x86), but somehow, the beta directory only contains the linux x86-64 target.

I have no idea how I got in this situation, and I also have no idea how to remedy it. `rust target list` shows all five, and I haven't found a per-toolchain way of installing targets. I guess a way around would be to remove targets and re-add them?

**Comment by Diggsey** [comment]
This is the expected behaviour - targets are installed for a specific toolchain (if unspecified, they are installed to the currently active toolchain) - as to do otherwise would result in a quadratic increase in the number of components being installed.

When adding a target, you can specify a different toolchain using the `--toolchain` argument to rustup.
