### ISSUE TITLE
Allow `+toolchain` for rustup

### ISSUE THREAD

**Issue by tbu-** [rust-lang/rustup#1498]
It was surprising to me that I couldn't use the `+nightly` parameter on rustup for adding the `wasm32-unknown-unknown` target to nightly:
```
rustup +nightly target add wasm32-unknown-unknown
```
(and other combinations didn't work either). Instead I had to find the `--toolchain` parameter of `rustup target add`. It would be nice if `+nightly` would work on `rustup`, too.

**Comment by tbu-** [comment]
CC #1489.

**Comment by vi** [comment]
In addition to `+nightly` all of theese should also work:

* `rustup --toolchain=nightly target add wasm32-unknown-unknown`
* `rustup  target --toolchain=nightly add wasm32-unknown-unknown`

Also `rustup target --help` should mention `--toolchain` somewhere.

**Comment by pickfire** [comment]
I would like to do this. I noticed that `cargo` does not explicitly parse this but instead passes this to `rustc` to handle it. Should we check it on `rustup` side with internal function to list toolchains?

**Comment by BeniCheni** [comment]
Hi @pickfire, friendly note that from [this comment](https://github.com/rust-lang/rustup.rs/issues/1489#issuecomment-536380104) from #1489, I started working on the 2nd PR for +foo variant in the same scope of #2031. Should be able to push an update later today for +foo variant.

**Comment by pickfire** [comment]
@BeniCheni Yeah, but that's just for `which` right? I want to help out on this too.

**Comment by BeniCheni** [comment]
@pickfire, from [this comment](https://github.com/rust-lang/rustup.rs/issues/1489#issuecomment-536380104) from #1489:

> and then have #1498 provide the +foo variant.

> I'm interested in trying out. ...

From my comment there, I indicated my interest in working on #1498 here. But I'm happy to share, if you want to try out a PR for #1498 here.

Let me know if you are committed to this issue. If yes, I can check out other open issues. If no, I will continue to pick up this issue, since #2031 is in final shape.
