### ISSUE TITLE
Not enough space problem with rustup

### ISSUE THREAD

**Issue by mahdi-nasehiyan** [rust-lang/rustup#1502]
Hello.
I'm trying to use rustup on my Raspberry pi 1 B+ running raspbian stretch.
I'm using an 8Gb memory card for my RPi.
At first I had about 300Mb free and rustup was giving me an error about 'mktemp' failing.
I cleaned some spece and now I have About  600Mb and the installation process goes on for a few minutes and at the end it says "Not enough space" and aborts.
What should I do?
I can not switch to another sdcard because I have done so much on this raspbian image and I definitely can't start everything from scratch.
And I have removed ulmost every unnecessary program to free up some space ...
600Mb is not enough? Do I need more for installing rust toolchain?
I only need to compile a program written in rust and after that I will definitely uninstall rust compiler(I need the binary file only).
I really can't think of anything and I have been stuck on this problem for a few days now...

**Comment by kinnison** [comment]
Hi @iminsightman 

I'm really sorry that nobody got back to you before now.  I'm guessing you either solved this for yourself or else gave up on Rust.  I do hope it was the former and not the latter.

Unfortunately Rust toolchains are quite big and while you had a good chunk of space, toolchains can be up to a few gigabytes in size if you have lots selected.  In the *next* release of Rust (so 1.40.0) you might have a better chance because we've made significant improvements in the size of things.

Until then, `rustup` now supports the concept of a minimal installation profile which *might* be small enough for you.

Good luck, and if you have other problems, please let me know.

Thanks,

Daniel.
