### ISSUE TITLE
New rustup version doesn't install components (or update path) correctly

### ISSUE THREAD

**Issue by Sogomn** [rust-lang/rustup#1537]
After updating my rustup my shell can neither find rustc nor cargo anymore. I tried reinstalling everything, both stable and nightly. Worked fine before the update. PATH points to `/bin/` and `~/.cargo/bin/`.

![image](https://user-images.githubusercontent.com/40247521/48069390-afe36880-e1d5-11e8-9762-c45a87245910.png)

**Comment by Sogomn** [comment]
Same issue on a different device.
Apparently the symlinks in `/usr/bin/` are missing.

**Comment by faulesocke** [comment]
This is a void linux specific issue since we decided to remove the symlinks in /usr/bin in the package because someone came up with a (hopefully) better idea. Please complain in the void-linux/void-packages repo ;)

See also:
#1559 
https://github.com/void-linux/void-packages/pull/5293
https://github.com/void-linux/void-packages/pull/4980
https://github.com/void-linux/void-packages/pull/4528

**Comment by Sogomn** [comment]
Hmh okay. I went back to using the manual installer which seems to work fine.
