### ISSUE TITLE
Merge some of the crates (probably only rustup and rustup-dist)

### ISSUE THREAD

**Issue by dwijnand** [rust-lang/rustup#1644]
Split out from https://github.com/rust-lang/rustup.rs/issues/1611

The current crates tree is:

```
rustup-win-installer
└── rustup
    └── rustup-dist
        └── rustup-utils
            └── download

[dev-dependencies]
└── rustup-mock
```

WDYT about squashing that down to:

```
rustup-win-installer
└── rustup
```

And the only reason to keep those separate is because I can't run rustup-win-installer with its build.rs.  WDYT?

**Comment by nrc** [comment]
:+1: I'm keen on this and have contemplated something similar myself in the past. I'd also be keen to turn Rustup into a workspace, rather than a bunch of separate crates. I think it might make sense to keep rustup-mock separate since it is only used for testing and is quite different from the rest. I think it might also make sense to keep download separate, if it can be a strongly encapsulated crate (ideally shared with Cargo).

**Comment by dwijnand** [comment]
Ok I'll make it a workspace and keep download separate.  But rustup-mock I was just going to have as a module of the rustup tests (much like the "support" module in cargo's testsuite).

**Comment by dwijnand** [comment]
Root layout-wise @kinnison prefers

```
/Cargo.lock
/Cargo.toml
/src/ (the sources of the rustup crate)
/download/ (the separate download crate)
```

The code in `rustup-mock` would either become `#[cfg(test)]`-gated code in the rustup crate, or directly a module in the tests.
