### ISSUE TITLE
wasm64-unknown-unknown target broken

### ISSUE THREAD

**Issue by mcandre** [rust-lang/rustup#1661]
**Problem**

I am able to install the `wasm32-unknown-unknown` target with rustup. However, when I try to install the 64-bit edition, then rustup complains:

```console
error: toolchain 'nightly-x86_64-unknown-linux-gnu' does not contain component 'rust-std' for target 'wasm64-unknown-unknown'
```

**Steps**

1. `rustup target add wasm64-unknown-unknown`

**Notes**

Output of `rustup --version`:

```console
rustup 1.16.0 (beab5ac2b 2018-12-06)
```

Output of `rustup show`:

```console
Default host: x86_64-unknown-linux-gnu

installed toolchains
--------------------

stable-x86_64-unknown-linux-gnu
nightly-x86_64-unknown-linux-gnu (default)

installed targets for active toolchain
--------------------------------------

wasm32-unknown-unknown
x86_64-unknown-linux-gnu

active toolchain
----------------

nightly-x86_64-unknown-linux-gnu (default)
rustc 1.34.0-nightly (e54494727 2019-02-13)
```

**Workaround**

In order to circumvent this problem, I am building 32-bit WASM artifacts, or else using emcc and C/C++ to produce 64-bit WASM artifacts. Funnily enough, emcc has the reverse problem and so is unable to build 32-bit artifacts out of the box.

**Comment by cuviper** [comment]
The target will have to be added and built in the main rust repo, and then rustup can fetch it.

cc @rust-lang/wg-wasm

**Comment by alexcrichton** [comment]
At this time this is expected because a 64 bit target for was does not exist (it's not even spec'd!)

It sounds like there may be some confusion about targets though? For Rust all wasm targets start with wasm32

**Comment by Pauan** [comment]
To clarify, there are two things here: the bitness of your computer, and the bitness of the wasm runtime.

The bitness of your computer might be either 32-bit or 64-bit: either are fine.

The bitness of the wasm runtime is *always* 32-bits. This is *mandated* by the official wasm specification. That's why it's called `wasm32-*`.

So even if you are building on a 64-bit system, and even if you're running the wasm program on a 64-bit system, it's still using a 32-bit wasm interpreter.

So as @alexcrichton said, `wasm64` doesn't exist, but that's okay, because it's possible to build and run `wasm32` on a 64-bit system.

**Comment by gilescope** [comment]
wasm64-unknown-unknown is on the platform list as existing now but seems std lib isn't precompiled for it when I try it.

**Comment by CryZe** [comment]
I'm not seeing it on the target list:
```
...
thumbv8m.main-none-eabihf (installed)
wasm32-unknown-emscripten
wasm32-unknown-unknown (installed)
wasm32-wasi (installed)
x86_64-apple-darwin
...
```
and I don't think it's supposed to be there. It's a tier 3 target with no prebuilt std.
