### ISSUE TITLE
No rust-doc installed for stable-armv7-unknown-linux-gnueabihf

### ISSUE THREAD

**Issue by PeterOGB** [rust-lang/rustup#1665]
**Problem**

I've installed Rust on x86-64 and Raspberry Pi platforms.  rustup doc only works on the X86-64 and fails on the PI due to  /home/pi/.rustup/toolchains/stable-armv7-unknown-linux-gnueabihf/share/doc/rust/html not exisiting.

There seems to be no rust-doc built for armv7....

pi@Pi3BPlus1:~ $ rustup install nightly
info: syncing channel updates for 'nightly-armv7-unknown-linux-gnueabihf'
info: latest update on 2019-02-18, rust version 1.34.0-nightly (9a3392e17 2019-02-17)
info: downloading component 'rustc'
 69.3 MiB /  69.3 MiB (100 %) 963.2 KiB/s ETA:   0 s                 
info: downloading component 'rust-std'
 51.9 MiB /  51.9 MiB (100 %) 960.0 KiB/s ETA:   0 s                
info: downloading component 'cargo'
  3.8 MiB /   3.8 MiB (100 %) 959.7 KiB/s ETA:   0 s                
info: installing component 'rustc'
info: installing component 'rust-std'
info: installing component 'cargo'

  nightly-armv7-unknown-linux-gnueabihf installed - rustc 1.34.0-nightly (9a3392e17 2019-02-17)

**Steps**

1.  runing  "rustup doc"  produces and error pop-up about index.html missing.

pi@Pi3BPlus1:~ $ rustup --version
rustup 1.16.0 (beab5ac2b 2018-12-06)

pi@Pi3BPlus1:~ $ rustup show
Default host: armv7-unknown-linux-gnueabihf

installed toolchains
--------------------

stable-armv7-unknown-linux-gnueabihf
nightly-armv7-unknown-linux-gnueabihf

active toolchain
----------------

stable-armv7-unknown-linux-gnueabihf (default)
rustc 1.32.0 (9fda7c223 2019-01-16)

**Comment by corvinux** [comment]
I've the same problem with no rust-doc on my JollaC phone. I tried stable and nightly toolchains, no **/doc/rust/html/** directory in either !

[nemo@JollaC ~]$ rustup --version
rustup 1.16.0 (beab5ac2b 2018-12-06)
[nemo@JollaC ~]$ rustc -V
rustc 1.35.0-nightly (f22dca0a1 2019-03-05)
[nemo@JollaC ~]$ cargo -V
cargo 1.34.0-nightly (5c6aa46e6 2019-02-22)
[nemo@JollaC ~]$ rustup default stable
info: using existing install for 'stable-armv7-unknown-linux-gnueabihf'
info: default toolchain set to 'stable-armv7-unknown-linux-gnueabihf'

  stable-armv7-unknown-linux-gnueabihf unchanged - rustc 1.33.0 (2aa4c46cf 2019-02-28)

`[nemo@JollaC ~]$ rustup show
Default host: armv7-unknown-linux-gnueabihf

installed toolchains
--------------------

stable-armv7-unknown-linux-gnueabihf (default)
nightly-armv7-unknown-linux-gnueabihf` 

I can't add any of otherwise listed components below:
[nemo@JollaC ~]$ rustup component list
cargo-armv7-unknown-linux-gnueabihf (default)
llvm-tools-preview-armv7-unknown-linux-gnueabihf
rls-armv7-unknown-linux-gnueabihf
rust-analysis-armv7-unknown-linux-gnueabihf
rust-src
rust-std-aarch64-apple-ios
rust-std-aarch64-fuchsia
rust-std-aarch64-linux-android
rust-std-aarch64-pc-windows-msvc
rust-std-aarch64-unknown-cloudabi
rust-std-aarch64-unknown-linux-gnu
rust-std-aarch64-unknown-linux-musl
rust-std-arm-linux-androideabi
rust-std-arm-unknown-linux-gnueabi
rust-std-arm-unknown-linux-gnueabihf
rust-std-arm-unknown-linux-musleabi
rust-std-arm-unknown-linux-musleabihf
rust-std-armebv7r-none-eabi
rust-std-armebv7r-none-eabihf
rust-std-armv5te-unknown-linux-gnueabi
rust-std-armv5te-unknown-linux-musleabi
rust-std-armv7-apple-ios
rust-std-armv7-linux-androideabi
rust-std-armv7-unknown-linux-gnueabihf (default)
rust-std-armv7-unknown-linux-musleabihf
rust-std-armv7r-none-eabi
rust-std-armv7r-none-eabihf
rust-std-armv7s-apple-ios
rust-std-asmjs-unknown-emscripten
rust-std-i386-apple-ios
rust-std-i586-pc-windows-msvc
rust-std-i586-unknown-linux-gnu
rust-std-i586-unknown-linux-musl
rust-std-i686-apple-darwin
rust-std-i686-linux-android
rust-std-i686-pc-windows-gnu
rust-std-i686-pc-windows-msvc
rust-std-i686-unknown-freebsd
rust-std-i686-unknown-linux-gnu
rust-std-i686-unknown-linux-musl
rust-std-mips-unknown-linux-gnu
rust-std-mips-unknown-linux-musl
rust-std-mips64-unknown-linux-gnuabi64
rust-std-mips64el-unknown-linux-gnuabi64
rust-std-mipsel-unknown-linux-gnu
rust-std-mipsel-unknown-linux-musl
rust-std-powerpc-unknown-linux-gnu
rust-std-powerpc64-unknown-linux-gnu
rust-std-powerpc64le-unknown-linux-gnu
rust-std-riscv32imac-unknown-none-elf
rust-std-riscv32imc-unknown-none-elf
rust-std-s390x-unknown-linux-gnu
rust-std-sparc64-unknown-linux-gnu
rust-std-sparcv9-sun-solaris
rust-std-thumbv6m-none-eabi
rust-std-thumbv7em-none-eabi
rust-std-thumbv7em-none-eabihf
rust-std-thumbv7m-none-eabi
rust-std-thumbv7neon-linux-androideabi
rust-std-thumbv7neon-unknown-linux-gnueabihf
rust-std-thumbv8m.main-none-eabi
rust-std-wasm32-unknown-emscripten
rust-std-wasm32-unknown-unknown
rust-std-x86_64-apple-darwin
rust-std-x86_64-apple-ios
rust-std-x86_64-fortanix-unknown-sgx
rust-std-x86_64-fuchsia
rust-std-x86_64-linux-android
rust-std-x86_64-pc-windows-gnu
rust-std-x86_64-pc-windows-msvc
rust-std-x86_64-rumprun-netbsd
rust-std-x86_64-sun-solaris
rust-std-x86_64-unknown-cloudabi
rust-std-x86_64-unknown-freebsd
rust-std-x86_64-unknown-linux-gnu
rust-std-x86_64-unknown-linux-gnux32
rust-std-x86_64-unknown-linux-musl
rust-std-x86_64-unknown-netbsd
rust-std-x86_64-unknown-redox
rustc-armv7-unknown-linux-gnueabihf (default)
rustfmt-armv7-unknown-linux-gnueabihf

**Comment by kinnison** [comment]
Yes, armv7 is tier 2 and rust-doc doesn't build for it right now.

We could add better error messages for `rustup doc` perhaps, and we'll likely do that when we add support for profiles.  Until then, I don't really see the value in this issue so I'm closing it.

You can reopen it if you feel there's actually something *rustup* can do for you for this situation.

**Comment by PeterOGB** [comment]
I don't care any more.  I found rust to be just to different for the sake of being different for my liking.
I have no interest in it anymore

**Comment by kinnison** [comment]
@PeterOGB I'm sorry to hear that Rust didn't fit well with you, and I wish you all the best.

**Comment by shenki** [comment]
I hit this issue while attempting to use the docs on a aarch64 Chromebook.

What's the issue that needs to be resolved? I had a quick search and couldn't find an issue relating to building docs for arm. 

I am surprised that html documentation is architecture specific. Can we install the x86 package as a workaround?

**Comment by kinnison** [comment]
Unfortunately the documentation is actually architecture specific to some extent.  It's unclear to me why docs fail to build on those architectures, but you could try opening an issue on rust-lang/rust about improving matters?  There's little we can do in rustup itself really :(

**Comment by shenki** [comment]
You missed the second half of my question. How would a user install the x86 documentation?

**Comment by kinnison** [comment]
@shenki Oops sorry, You could install an x86 toolchain just to use the docs, but that will use the space for the compiler and cargo too :/

**Comment by mdinsmore** [comment]
> Yes, armv7 is tier 2 and rust-doc doesn't build for it right now.
> 
> We could add better error messages for `rustup doc` perhaps, and we'll likely do that when we add support for profiles. Until then, I don't really see the value in this issue so I'm closing it.
> 
> You can reopen it if you feel there's actually something _rustup_ can do for you for this situation.

Yes a better error message would be a good interim solution perhaps pointing towards the online version of the documentation https://doc.rust-lang.org/book/#the-rust-programming-language which might help Tier 2 users feel less like second class citizens!

**Comment by kinnison** [comment]
@mdinsmore An interesting idea.  Could you open a fresh issue describing the situation you're in, and a proposal for how to alter `rustup doc` to support it?

**Comment by jerrychong25** [comment]
For old Raspberry Pi, it's using **armv7-unknown-linux-musleabihf** platform.

Possible to support it soon?

**Comment by rbtcollins** [comment]
As already mentioned, this requires rust-docs to build the docs.
