### ISSUE TITLE
Changelog for 1.16 and 1.17

### ISSUE THREAD

**Issue by tesuji** [rust-lang/rustup#1686]
Does `rustup`  1.16 and 1.17 bring any new improments over older versions?
Those new features would be better documented in CHANGLOG.md.

**Comment by kinnison** [comment]
When we were discussing the 1.17.0 release in our weekly meetings we decided that as CHANGELOG.md hadn't been touched since 1.13.0 we were okay with not bothering for 1.17.0.

If you wanted to generate a backfill for it, I'd be pleased to review it.  But I don't have the time/mental space for it right now myself.
