### ISSUE TITLE
Include completion files instead of generating them on the fly

### ISSUE THREAD

**Issue by dmarcoux** [rust-lang/rustup#1706]
**Describe the problem you are trying to solve**
I am working on packaging _rustup_ for _openSUSE_ and generating completion files on the fly cannot guarantee reproducible builds (because the generated completion files could differ).

**Describe the solution you'd like**
I would like that the completion files are included in the source, so they are always the same and are also easily packaged. This is the usual way to do it. Having to redirect the output of commands in a package build system is somewhat weird and unusual.

**Notes**
The package: https://build.opensuse.org/package/show/home:dmarcoux/rustup.rs

**Comment by dwijnand** [comment]
The way that rustup does it is apparently the same way `npm completion` does it and the way cargo wants to do it too: https://github.com/rust-lang/cargo/issues/6645

Rather than revert back to flat files, could can we continue to generate them in a way that guarantees reproducibility?  How does packaging on openSUSE deal with other resources being generated on the fly and reproducibility concerns?

**Comment by bmwiedemann** [comment]
From the reproducible builds perspective, it is OK to generate files on the fly as long as this happens in a deterministic way. From `echo foo > output` to `gcc -o output $input` it is all fine.
https://github.com/bmwiedemann/theunreproduciblepackage lists 10 known ways of introducing non-determinism. I'll test and report back if any of them applies here - and which.

**Comment by bmwiedemann** [comment]
Test done: all outputs of the `home:dmarcoux/rustup.rs` package are reproducible.

**Comment by dmarcoux** [comment]
Thank you very much @bmwiedemann.

I'm closing this issue.

**Comment by dwijnand** [comment]
Excellent news.  Thank you, both.
