### ISSUE TITLE
Support command rustup update nightly/yyyy-MM-dd

### ISSUE THREAD

**Issue by liuchong** [rust-lang/rustup#1713]
When we install nightly build of rust, some components may break.
With page https://rust-lang.github.io/rustup-components-history/ we know which version we could use, but we must specify the toolchain, like `rustup update nightly-2019-03-15`, and it will be a specified toolchain `nightly-2019-03-15-x86_64...` but not just `nightly-x86...`. 

I would like to install the specified date of build, and still keep it as 'nightly', not a dated one. So maybe a command like `rustup update nightly/2019-03-15` is nice.

e.g. assume we have `rustup toolchain list` with init output:
```
nightly-x86_64-unknown-linux-gnu (default)
```
then,
`rustup update nightly-2019-03-15` and then `rustup toolchain list` with output:
```
nightly-2019-03-15-x86_64-unknown-linux-gnu
nightly-x86_64-unknown-linux-gnu (default)
```
while,
`rustup update nightly/2019-03-15` and then `rustup toolchain list` with output:
```
nightly-x86_64-unknown-linux-gnu (default)
```

**Comment by mikeyhew** [comment]
I just want to re-explain the problem from my perspective, in case the maintainers are having trouble understanding the issue.

I develop with nightly by default. To upgrade nightly, I run `rustup update nightly`, which works great, when it works. But these days the `rls` component is often broken, and `rustup update nightly` doesn't work.

The common workaround is to go to https://rust-lang.github.io/rustup-components-history/ to see the last nightly version for which all of the components that I have installed are in a working state, then run `rustup toolchain install nightly-yyyy-MM-dd` for that date. Then I can run `rustup default nightly-yyyy-MM-dd` so that it becomes the default version.

There are two main annoyances here:

1. Having to go to the page in the browser to find the latest nightly that works. Rustup knows which components you have installed, and could figure this out for you. It's also something that's not entirely obvious how to do: rustup gives you instructions, saying to go to https://rust-lang-nursery.github.io/rust-toolstate, but that webpage tells you the commit that broke each component and not which nightly to use. (The one to try is the nightly from the day *before* it was broken.)
2. If I run `rustup default nightly-yyyy-MM-dd`, then the next time I run `rustup update nightly`, nightly will still not be the default toolchain, and I'll have to change the default toolchain again.

**Comment by rbtcollins** [comment]
Your description of your intent doesn't entirely match the feature you're asking for. Your feature description enables the ability to install any arbitrary date from ever 'as' nightly. Your described intent is the ability to get the latest nightly that had all the components you have installed build successfully to install with minimal fuss.

We may be able to do the latter in a more focused fashion than requiring you to look up a known-good-date and punch that in.

e.g. should "rustup update nightly", when the latest nightly is missing a component, automatically grab an older nightly that is still newer than what you have, so that you do get an upgrade, and install that as well as telling you about the situation it encountered?

**Comment by azriel91** [comment]
^ That's what most people would be happy with I believe, and surprises mitigated with an opt-in parameter

**Comment by liuchong** [comment]
I think don't want any automatically things, which do more than what I exactly expect for. A feature rustup install nightly@yyyy-MM-dd `as nightly` is what I want. 
I've tried to make an implement, not good enough to merge. maybe I could make a better one later, when I have time :joy_cat:

**Comment by kinnison** [comment]
I'm more inclined to add a `--date` argument to install/update to effectively set the date for an attempted install/update.  Adding `@date` seems arcane, adding an `as foo` ditto.

So the idea would be you could do `rustup toolchain install --date YYYY-MM-DD nightly` and if a `rustup update nightly` failed, you could try `rustup update --date YYYY-MM-DD nightly` but it'd be up to you to work out which date matched.

Walking the history is expensive and slow.  We'd need to have a smarter server-side solution first.

**Comment by liuchong** [comment]
> I'm more inclined to add a `--date` argument to install/update to effectively set the date for an attempted install/update. Adding `@date` seems arcane, adding an `as foo` ditto.
> ...

Seems reasonable. ( and ... the `@date` is just for explanation, not for real impl )
`--date` seems like an install/update against a snapshot on a date, is also acceptable I think.

**Comment by ntruessel** [comment]
Is someone still working on this? Otherwise I'd like to give it a try and adjust the code from #1714 to use a `--date` flag.

**Comment by kinnison** [comment]
We currently have, in master, waiting for a release, an automatic backwalker for nightly which copes with finding the right version for the installed component set, combined with a facility to specify additional components at install time, leading to: `rustup toolchain install nightly -c clippy -c rustfmt` working for most people's use-cases.  If there is still a use-case for a specific date then I'd love to see a replacement offering for #1714 which adds a `--date` flag to `rustup toolchain install` with the caveat that it'd likely be best to start afresh with the patch due to the amount of code change since March.

**Comment by ntruessel** [comment]
The backwalker definitely resolves my issue. In case you'd like to see this implemented anyway, I'm still willing to work on it.

**Comment by kinnison** [comment]
I think there's probably less value in it than there used to be.  I'd quite like to allow a `nightly-$DATE` installation to be converted into a `nightly` (`rustup toolchain rename` or something like) but that's entirely orthogonal to the goal that this issue originally set out to resolve.  Perhaps this issue should be closed if @liuchong agrees?

**Comment by liuchong** [comment]
Yes, I agree, let me close it.
Maybe we need another issue for the `rustup toolchain rename` 👀
