### ISSUE TITLE
`RUSTUP_INIT_SKIP_PATH_CHECK=yes` doesn't work

### ISSUE THREAD

**Issue by mati865** [rust-lang/rustup#1737]
**Problem**

I'm trying to install `rustup` in Docker container of Ubuntu alonside the toolchain I'm working on:
```
# export RUSTUP_INIT_SKIP_PATH_CHECK=yes
# curl https://sh.rustup.rs -sSf | sh
info: downloading installer
warning: it looks like you have an existing installation of Rust
warning: rustup cannot be installed alongside Rust. Please uninstall first
warning: run `/usr/local/lib/rustlib/uninstall.sh` as root to uninstall Rust
error: cannot install while Rust is installed
```

**Steps**

1. Install Rust with standalone installer.
2. Rustup won't install even with `RUSTUP_INIT_SKIP_PATH_CHECK=yes`.

**Comment by kinnison** [comment]
Fair point.  There appears to be two places in `self_update.rs` where this kind of check is done, and only one is guarded with the environment variable support...

This one is guarded: https://github.com/rust-lang/rustup.rs/blob/master/src/cli/self_update.rs#L356

This one is not: https://github.com/rust-lang/rustup.rs/blob/master/src/cli/self_update.rs#L385

It's worth noting that the first (guarded) one is checking for rustc and/or cargo in the PATH, whereas the second is explicitly looking for a preinstalled rust toolchain using the standalone installer, by looking for the installer manifest and uninstaller, not for rustc/cargo on the PATH.

I'd suggest not installing the standalone toolchain in that fashion if you also want rustup since you can put it somewhere else and then use `rustup toolchain link local /path/to/toolchain` to bring your toolchain into the rustup arena.

If you have strong reason for using the *installer* form of the toolchain *and* rustup, then please let me know and I'll look at adding a `RUSTUP_INIT_SKIP_PREINSTALLED_TOOLCHAIN_CHECK` or similar.  If, on the other hand, the approach above would work for you, then feel free to close this issue.

Thanks,

D.

**Comment by mati865** [comment]
When working on Rust I'm often comparing my patched toolchain to released versions and I don't see why it should matter whether it's installed to `/usr/local` or somewhere else.

Anyway I'll just use customized Docker Image with preinstalled Rustup.
