### ISSUE TITLE
invalid (valid) channel name in rust-toolchain

### ISSUE THREAD

**Issue by mykhailokrainik** [rust-lang/rustup#1745]
**Problem**

I'm trying to get the rust version I need through specifying the version in rust-toolchain
**Steps**

1. Create rust-toolchain in project directory, which contains `nightly-2018-11-27-x86_64-unknown-linux-gnu` without any space in the word 
2. run $rustc -V
3. got error
```
rustc -V
error: invalid channel name 'nightly-2018-11-27-x86_64-unknown-linux-gnu' in '/path/to/project/rust-toolchain'
info: caused by: target triple in channel name 'nightly-2018-11-27-x86_64-unknown-linux-gnu'
```
4. check with cargo
```
$ cargo +nightly-2018-11-27-x86_64-unknown-linux-gnu -V
cargo 1.32.0-nightly (b3d0b2e54 2018-11-15)
```
**Possible Solution(s)**

**Notes**

Output of `rustup --version`:
Output of `rustup show`:

$ rustup --version
rustup 1.17.0 (069c88ed6 2019-03-05)

$ rustup show
Default host: x86_64-unknown-linux-gnu

installed toolchains
--------------------

stable-x86_64-unknown-linux-gnu (default)
beta-x86_64-unknown-linux-gnu
nightly-2018-11-27-x86_64-unknown-linux-gnu
nightly-x86_64-unknown-linux-gnu

active toolchain
----------------
(error: invalid channel name 'nightly-2018-11-27-x86_64-unknown-linux-gnu' in '/path/to/project/rust-toolchain')

**Comment by mykhailokrainik** [comment]
@kinnison

**Comment by kinnison** [comment]
Hi @mikhail-krainik,

Thanks for reporting this.

For the edification of others, we had a brief discussion on the rust developers discord in the Cargo channel about all this, becuase Mikhail was trying to force the use of a specific toolchain (including specific architecture) by means of writing a cargo plugin to do this.  I asked why he didn't use `rust-toolchain` and this bug report is the result.

It's not clear *yet* whether the right answer is to improve the error message to suggest removing the architecture from the toolchain channel name (or some other improvement to the error message) or to deal with it in some silent, or warning-like, way.

@Nemo157 rightly stated that to silently accept the arch **iff** it's equal to the host arch might be a bit too dangerous since it'd mask an issue for others potentially.

Right now, we're not certain what the right approach will be, so further discussion is required.

**Comment by Qquanwei** [comment]
I have the same error 
![image](https://user-images.githubusercontent.com/9263655/56263620-35b8f780-6116-11e9-9bd8-37e6098e545b.png)

**Comment by kinnison** [comment]
@Qquanwei Thank you for confirming that this problem exists for others.  Could you provide any insight into *why* the `rust-toolchain` in that directory contains a host architecture as well as the channel name?  What is _remacs_ trying to achieve by doing this?

Also, do you have an opinion on the options mentioned in https://github.com/rust-lang/rustup.rs/issues/1745#issuecomment-481313146 and/or any further ideas to improve the UX here?

**Comment by Qquanwei** [comment]
This error is not a common error , when I re-install remacs environment it not appear for me. 

the only thing that I do is `rustup default xxx` .

**Comment by kinnison** [comment]
@Qquanwei Something else must be putting that file down then - I suggest that if it happens again you grep around looking for what created the file.  In the meantime, I'm glad the problem has gone away for you for now.

**Comment by jethrogb** [comment]
I'm getting the same errors when using `rustup toolchain link`. The linked toolchain works fine when using `<TOOL> +<TOOLCHAIN>` syntax, but not when using the `rust-toolchain` file.

**Comment by kinnison** [comment]
Interesting, you're quite right it does behave badly like that.  Hmm...

**Comment by davehylands** [comment]
I'm running into this as well. The toolchain I built is hooked into rustup using `rustup toolchain link`

I can do `cargo +$(cat rust-toolchain) run` and it works fine. But if I try just plain `cargo run` it fails with the invalid channel name error.

Setting the toolchain to the default using rustup also allows `cargo run` to work (if I remove the rust-toolchain file).

**Comment by davehylands** [comment]
Using `RUST_TOOLCHAIN=my-2019-09-05-llvm8 cargo run` also seems to work. Is there a way I can name my toolchain that will allow it to work with the rust-toolchain file which doesn't match one of the standard names?

**Comment by davehylands** [comment]
And `rustup show` also displays the invalid channel name error when rust-toolchain contains `my-2019-09-05-llvm8`

**Comment by kinnison** [comment]
I agree that these later examples are not good, so I'm going to try and resolve this.  Whether I end up with something the OP is happy with or not, I'm not sure I can predict; but I'll see what I can do.

**Comment by chostrander** [comment]
A little more context on this issue, I am trying to deploy a Rust Application to Heroku, and am using Rocket for my REST API.  This needs nightly, so I am trying to specify to use the nightly version instead of stable and am getting this error. (because I need to specify it in the rust-toolchain file.
