### ISSUE TITLE
Confusing error when trying to add new targets with non-default host

### ISSUE THREAD

**Issue by jdm** [rust-lang/rustup#1756]
**Problem**
I installed rustup by passing `--default-toolchain none --default-host aarch64-unknown-linux-gnu`, then in a directory with a `rust-toolchain` containing `nightly-2019-03-26` I tried to run `rustup target add --toolchain nightly-2019-03-26 aarch64-unknown-linux-gnu`, which failed with a confusing error message: `error: toolchain 'nightly-2019-03-26-x86_64-unknown-linux-gnu' does not support components`. The way I resolved this was to remove ~/.rustup and ~/.cargo, then reinstalled rustup with the default arguments.

**Steps**

1. Install with `--default-toolchain none --default-host aarch64-unknown-linux-gnu`
2. Set the current toolchain to some specific nightly version
3. Run `rustup target add --toolchain nightly-2019-03-26 aarch64-unknown-linux-gnu`

**Possible Solution(s)**

**Notes**

Output of `rustup --version`: rustup 1.17.0 (069c88ed6 2019-03-05)
Output of `rustup show`:
```
Default host: x86_64-unknown-linux-gnu

installed toolchains
--------------------

stable-x86_64-unknown-linux-gnu
nightly-2019-03-26-x86_64-unknown-linux-gnu

installed targets for active toolchain
--------------------------------------

aarch64-unknown-linux-gnu
x86_64-unknown-linux-gnu

active toolchain
----------------

nightly-2019-03-26-x86_64-unknown-linux-gnu (overridden by '/home/servobuild/servo/rust-toolchain')
rustc 1.35.0-nightly (4c27fb19b 2019-03-25)
```

**Comment by kinnison** [comment]
Hi @jdm,

This bug report is really quite confusing to me -- So if you could bear with me, I'd like to clarify what you have, what you wanted, what you did, and what happened...

1. You appear to have an x86_64 linux system based on the `default host` shown above.
2. You tried to install (presumably x86_64) rustup with no toolchain (skipping the install of stable) but with `aarch64` as the architecture of the host
3. Then in a directory which contained a `rust-toolchain` file specifying a particular nightly version, you attempted to add a component to a toolchain which wasn't installed (yet)
4. The error message which was given to you was confusing since it talked about a toolchain not supporting components, when in reality it should have said that the toolchain wasn't installed.

What I *think* you wanted was to have a Rust installation with no `stable` toolchain, with a specific `nightly` toolchain, in which you had added the `aarch64` target so that you can cross-build for `aarch64` on your `x86_64` host computer.

Does that sound right?

If so, then we need to improve the error message around the "not supporting components" part of your story because really it should say "toolchain X is not installed, try running `rustup toolchain install X` first".

In addition, your setting of `default-host` when installing rustup is very worrisome/confusing to me since I'd expect that to result in the installation of `aarch64` toolchains on your `x86_64` system.

Please let me know if I've got any of that wrong, and then we can begin to sort out the right set of fixes to apply to rustup.

Thanks,

D.

**Comment by jdm** [comment]
@kinnison Your 1-4 bullets are all correct, as is your summary of what I was trying to achieve.

**Comment by kinnison** [comment]
OK cool, so... Your mistake was thinking you should set the host to aarch64 in order to get a compiler capable of *targetting* aarch64.  Our mistake was letting that happen without warning.

Separately there is a confusing error message where you attempt to add a component to a not-yet-installed toolchain which we could do with improving.

For you, short term, a sequence of approx.

1. `rustup-init --default-toolchain none`
2. `rustup toolchain install nightly-2019-03-26`
3. `rustup target add --toolchain nightly-2019-03-26 aarch64-unknown-linux-gnu`

Should give you the expected single toolchain, for nightly of 26th March, capable of running on your system, capable of targetting aarch64.

For us, we need to sort a better error message for the target/component add to a not-installed(-yet) toolchain.

Is that fair? Does it cover everything?

**Comment by jdm** [comment]
I already came up with a solution locally, but thanks for trying to address my original intention. And yes, a more specific error message in that case would be a good outcome from my point of view.

**Comment by kinnison** [comment]
Excellent, I'm glad you're making progress.  I'll self-assign this issue and try and write an error message patch.

**Comment by kinnison** [comment]
I have tested this locally and get the following sequence:

```console
demo@somniloquy:~$ ~dsilvers/dev-git/rustup.rs/target/debug/rustup-init --default-toolchain none --default-host aarch64-unknown-linux-gnu

Welcome to Rust!

This will download and install the official compiler for the Rust programming 
language, and its package manager, Cargo.

It will add the cargo, rustc, rustup and other commands to Cargo's bin 
directory, located at:

  /home/demo/.cargo/bin

This path will then be added to your PATH environment variable by modifying the
profile file located at:

  /home/demo/.profile

You can uninstall at any time with rustup self uninstall and these changes will
be reverted.

Current installation options:

   default host triple: aarch64-unknown-linux-gnu
     default toolchain: none
  modify PATH variable: yes

1) Proceed with installation (default)
2) Customize installation
3) Cancel installation
>1

info: skipping toolchain installation


Rust is installed now. Great!

To get started you need Cargo's bin directory ($HOME/.cargo/bin) in your PATH 
environment variable. Next time you log in this will be done automatically.

To configure your current shell run source $HOME/.cargo/env
demo@somniloquy:~$ source .cargo/env
demo@somniloquy:~$ ls
demo@somniloquy:~$ mkdir foo
demo@somniloquy:~$ cd foo
demo@somniloquy:~/foo$ echo nightly-2019-03-26 > rust-toolchain
demo@somniloquy:~/foo$ rustup target add --toolchain nightly-2019-03-26 aarch64-unknown-linux-gnu
error: toolchain 'nightly-2019-03-26-x86_64-unknown-linux-gnu' is not installed
demo@somniloquy:~/foo$ 
```
The error there looks sane to me, so I wonder how you managed to get that error message at all.

Could you please try and reproduce the error for me, and give me a console log?

**Comment by jdm** [comment]
I can't reproduce it now. Very mysterious.
