### ISSUE TITLE
rustup/rust should not occupy home directory

### ISSUE THREAD

**Issue by drozdowsky** [rust-lang/rustup#1879]
**Describe the problem you are trying to solve**
Hello,
I see three new folders in my clean and nice $HOME directory.
.cargo, .multirust, .rustup - none should be there in my opinion.

**Describe the solution you'd like**
Let user customize path at the installation.

Also the env script `source $HOME/.cargo/env` should be `. $HOME/.cargo/env` to be POSIX (?) compliant

Thank you and have a nice day :)

**Comment by kinnison** [comment]
Hi,

`rustup` as a tool is installed into your home directory.  As such the `.cargo` and the `.rustup` directories are very much expected.  The presence of a `.multirust` directory is a little worrying though unless you've installed a version of rustup older than one month ago, since we removed the last of that compatibility code back then.

While you're quite correct regarding `source` vs `.` for POSIX correctness, 99% of our users use one of `bash`, `zsh`, or `fish`, as their shell and as such `source` is much more easily read and understood.

Given all that, do you honestly feel any of this remains issue-worthy, or shall we close this out?

Thanks,

D.

**Comment by drozdowsky** [comment]
Hi, 
I have used rustup from void linux repository so it is possible that I have old version of rustup.  
I feel like this is issue-worthy I should have a choice where rustup/cargo is installed. 
E.G. my home folder can be mounted on other partition with not that much size available or I just don't like having everything in $HOME where it should be in $HOME/.local or /usr/bin/local.  
Of course I do not demand anything if community feels like it is not needed you can close this one.  
Best regards,  
H.

**Comment by kinnison** [comment]
It's quite probable you got something older.  The void-linux package was updated from 1.17.0 to 1.18.3 only a day ago.

Regarding `.cargo` you can set the `CARGO_HOME` environment variable before installing rustup to move that.  Regarding `.rustup` you can set `RUSTUP_HOME` to somewhere else too.

I hope you manage to arrange things to your liking, but I'm going to close this issue now.

Thanks, and good luck in your future rust endeavours.  If you have other issues, please don't hestitate to open an issue here, I'd rather educate and close, to create a resource for others, than to have you struggle in silence.
