### ISSUE TITLE
Error regarding home directory differences needs improvement.

### ISSUE THREAD

**Issue by AniketGupta07** [rust-lang/rustup#1884]
I tried to install rust in an android app termux but since it does not need root permission so running **curl https://sh.rustup.rs -sSf | sh**. Gives error:** rust $HOME differs from euid-obtained home directory**

**Comment by kinnison** [comment]
Because of the way that `rustup` operates, if the environment `$HOME` variable differs from the homedir provided by `getpwuid(geteuid())` then there could be surprising results during use.  As such we refuse to run in that situation.

Running *on* android is certainly not something we want to exclude from possibility, but it's also not something we can dedicate time to.  We recommend that you install Rust on a more traditional system (Linux, Windows, MacOS) and install the android tools and the android targets into that installation in order to build Rust code for Android.

If, on the other hand, you can come up with a tip/trick for making things work, I'd be happy to accept a PR for the docs.

**Comment by kinnison** [comment]
I would be helpful if `self_update.rs` explains what the two different values were when it raises this error.  Perhaps someone would like to do that?  I can mentor the change.

**Comment by calebcartwright** [comment]
:wave: @kinnison - I'd be interested in giving this a go, although it might be a bit of a stretch for me 😄 

Would a reasonable/simple approach be to have `home_mismatch()` return a tuple that contained the two different values (or at least the euid-obtained value) for home in addition to the bool that indicated whether there was a mismatch? Seems that would allow those different values to be added to the existing messages displayed from the [matching arms](https://github.com/rust-lang/rustup.rs/blob/master/src/cli/self_update.rs#L495)

**Comment by kinnison** [comment]
That would certainly be a fair approach yes.
