### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by thedrow** [rust-lang/rustup#1940]
We'd like to use rustup in Alpine Linux for which support was added in #1882.
The rustup-init binary is unfortunately [not available](https://static.rust-lang.org/rustup/dist/x86_64-unknown-linux-musl/rustup-init) for that platform although it appears on the README file.

Is there a plan for a new release soon which will include #1882?

**Comment by kinnison** [comment]
Opening an issue to discuss the release cadence isn't exactly normal practice, but I'll humour you and answer here anyway.  In the future if you want to discuss release cadence, please come onto our discord channel.

We can't release currently because we have test failures in Windows and a possible OpenSSL related issue on Linux.  If you're interested in helping with those, please come along to our Discord channel on the Rust language discord server and we'll be glad to discuss things.

**Comment by thedrow** [comment]
Sorry. I saw people doing the same before so I figured that's a normal practice here.

Thanks for the information.
I'll join and see what I can do.

**Comment by kinnison** [comment]
> Sorry. I saw people doing the same before so I figured that's a normal practice here.

That's okay, I'm trying to discourage it though :D

> Thanks for the information.
> I'll join and see what I can do.

Awesome!
