### ISSUE TITLE
Rustc, worker thread panicked, error: could not write output to main… : Permission denied  

### ISSUE THREAD

**Issue by MJarirUddin** [rust-lang/rustup#1948]
I am a beginner in Rust, using Ubuntu 18.04 LTS on WSL Windows 10. Please guide me about this error in the attachment.
![error 101](https://user-images.githubusercontent.com/47315358/61438833-cbecfb80-a959-11e9-885b-9c7fe8cdbe02.png)

\

Output of `rustup --version`:
rustup 1.18.3 (435397f48 2019-05-22)
Output of `rustup show`:
Default host: x86_64-unknown-linux-gnu

stable-x86_64-unknown-linux-gnu (default)
rustc 1.36.0 (a53f9df32 2019-07-03)

**Comment by kinnison** [comment]
Hi @MJarirUddin 

Welcome to the Rust community.  It looks like the panic is in the compiler rather than in Rustup itself.  As such, in theory the best place for you to file this would be https://github.com/rust-lang/rust *but* I can probably help you point at what might be going wrong.  If you have anti-virus programs running then there's a risk that they play about with files being opened an closed in such a way that the compiler might suffer from being unable to write its intermediate files.  It may be worth checking if you have such an AV and if so, see if you can get it to exclude the directories where you work on Rust projects.

I'm going to close this issue because it's not really a bug in `rustup` but if you can't resolve this yourself given the above hints, I strongly suggest you open an issue on the rust compiler itself to get it looked at.

Thanks,

D.

**Comment by MJarirUddin** [comment]
Thanks man! I got it resolved now, many thanks to you!!

**Comment by node** [comment]
> Thanks man! I got it resolved now, many thanks to you!!

Hi @MJarirUddin  cloud you please share your solution here ? I got the same issue .

**Comment by MJarirUddin** [comment]
> 

Hey, the problem was that the directory was not correct, I had to cd into the project's correct directory where the inited files and folders were present

**Comment by node** [comment]
> Hey, the problem was that the directory was not correct, I had to cd into the project's correct directory where the inited files and folders were present

Thx 👍
