### ISSUE TITLE
Should `$HOME/.cargo/bin` be appended or prepended to `PATH`?

### ISSUE THREAD

**Issue by iranvir** [rust-lang/rustup#2017]
**NOTE** This issue was reframed by @Kinnison after discussion.

We have reached the point that this needs further input from others.  The contention of the original issue was that by prepending to the `PATH` we end up surprising inexperienced users who go ahead and `cargo install` something which conflicts with something on their system such as `date` or `ls`.  The contention of @Kinnison is that to append rather than prepend to `PATH` would surprise more people who expect local binaries to override system binaries as that is the approach taken for years by everyone he knows.

The question is thusly, should we:

1. :rocket: retain the current prepending approach
2. :tada: switch to an appending approach
3. :smile: make it an option during installation
4. :confused: something else.

To express your opinion, please use the emoji reactions to this post, and if you feel the need, or if you choose 4, please post your ideas to the issue.  Once we have some sense of how users feel, we'll make a decision.  Thank you.

---

The OP's original post continues below

---

Currently the Rust installer adds $HOME/.cargo/bin to the start of PATH variable.

Adding .cargo at the start of PATH variable can cause potential problems if there's a Rust binary that has a name similar to that of a shell command like ls, cd, et al. 

A simple solution might be to add the $HOME/.cargo/bin to the end of PATH variable and also modifying .cargo/env file to have `export PATH="$PATH:$HOME/.cargo/bin"`

This is just a small tweak to keep the shell environment clean. If you think this is not necessary or, worse, harmful, please let me know the reasoning behind that.

**Comment by kinnison** [comment]
Right now, this is deliberate because it puts `rustup` and its associated proxies before any system installed cargo etc, making the user's experience more consistent with the majority of documentation out there (e.g. `cargo +nightly run` etc).  In addition since you can link a system supplied toolchain to a user-installed rustup, but not the other way around, it makes most sense for rustup to put `$HOME/.cargo/bin` onto the front of the `PATH` variable.

It is, in general, more consistent with UNIX philosophy to put the most specific paths first (user paths) and the least specific paths last (system paths) since that allows users to override system utilities.  System utilities which are security sensitive should be checking/resetting PATH as needed.  (e.g. like sudo)

I feel like this isn't something we want to do in `rustup` at this time, unless you can give me a more compelling argument against it (or show me that modern installers of this kind tend toward appending rather than prepending)

**Comment by iranvir** [comment]
I guess it makes sense from the strictest UNIX philosophy sense. Where the user knows what he/she is doing and can override the PATH variable to whatever is more convinent.

While I can't find another installer as a counterexample, I would still insist that for users who don't know (or care) about PATH variable can end up wasting tonnes of time even if they name their binary something innocent like data, or time.

**Comment by kinnison** [comment]
I think that while your efforts to protect people who might be confused/surprised should they `cargo install` something which conflicts in name with a system utility, I'd say that it's likely that the number of people who'd be surprised by that *not* replacing the behaviour could be even higher.

However, *I* am quite biassed in this, so what I think I'll do is retitle and edit the original posting you made to frame this as a question of "which is better?" and pop some labels on the issue asking for others to come and help.

**Comment by iranvir** [comment]
Thank you! That'd would be most helpful. :)

**Comment by iranvir** [comment]
Hey, @kinnison 
Crickets are chirping in this issue, should we close the issue rather than cluttering the project's issues tab? Nobody seems to be interested enough to chime in.

P.S: I don't know how long these things usually take, this is the first time I interacted with a community as large as this.

**Comment by pickfire** [comment]
Something else, I believe a better way is to have rustup uses the user's local binaries directory.

Say, if `~/.local/bin` exists and it is in the path, rustup should utilize that instead of using `.cargo/bin` and track the binaries that is installed with rustup.

The pros is that it can be able to group the local binaries along side with other users installed binary which makes searching local binaries easier. (I just did a search on `~/.local/bin` but then I need to find `~/.cargo/bin` again)

The cons is that tracking cargo installed dependencies may be harder as well as it might confuse users which local installed binary belongs to rustup, this can be solved by having rustup display all the rustup installed binaries.

**Comment by kinnison** [comment]
@pickfire I'm not sure that'd be better over-all, I'd rather just suggest that people don't put `~/.cargo/bin` in their path if they're worried about it.  @sranvir I'd give it a few more days at least.  Some people only turn up every few weeks :D

**Comment by iranvir** [comment]
:P That's okay, @kinnison  it's not that big of an issue anyways.
You replied to the issue pretty quickly, though

**Comment by kinnison** [comment]
> You replied to the issue pretty quickly, though

It's kinda my job as maintainer of the project :D

**Comment by kraiskil** [comment]
Just got started with rust yesterday, so this is a complete rust-newbie's opinion :)
Voted 4, because don't mess with my PATH!
Just have the installer tell that it got installed to $HOME/.cargo/bin (and while we are at it, what about asking where I want it installed?), and let me adjust my PATH. I much prefer interactive queries in these kind of installers. Then for automation, repetition or power-users, command line options to provide these answers to avoid the interactiveness.

**Comment by iranvir** [comment]
@kraiskil I can see where you are coming from. As a Rust Newbie I stuggle with this myself. But think about someone who is UNIX newbie. Do they have to learn about what PATH is? If we get too flexible, we get nowhere. Constraints kinda help us get over mundane stuff and go to work.

P.S: If you want rustup to not mess with your PATH just edit your .bashrc and ~/.cargo/env file.

**Comment by rbtcollins** [comment]
@kraiskil @sranvir there is an option to rustup-init to not modify the path already, explicitly for the use case of folk that want to do it themselves. But rustups *goal* is to make installation and 'get up and go' as easy as possible.

This really means that we need to work even if the user's machine has rustc globally installed via dpkg already. It is true that the use can then later do something confusing like installing a replacement bash via cargo, and it will be a problem. 

I think that that scenario is perhaps one to raise with the cargo team: should cargo permit installing a random crate binary that shadows an already installed system tool without warning? Thats quite different to rustups job, even though it is enabled via the same mechanism.

I'm going to close this though, since the direction of the consensus is quite clear.
