### ISSUE TITLE
Feature Request: Clean up download dir (partials etc) after successful full update run.

### ISSUE THREAD

**Issue by timw4mail** [rust-lang/rustup#2038]
**Edited by @kinnison to reflect decision later in thread**

It'd be good to have the downloads directory cleaned up if a full `update` (i.e. not a single-toolchain update) is completed.  That way any partial files etc lying around from failed updates will get cleaned up when we're in a position to believe that all is well and they wouldn't be reused.

I'm prepared to mentor someone in doing this, and suggest you talk to me on Discord about it.

---
Original from @timw4mail

**Describe the problem you are trying to solve**
After a while of use, the toolchains and downloads take up a decent amount of disk space. 

**Describe the solution you'd like**
Add a cleanup command, which would remove old downloads and toolchains, perhaps keeping just the most recent on each update channel.

**Comment by kinnison** [comment]
We do sometimes leave `.partial` and other download files, and that could definitely do with cleaning up.  The toolchains themselves only ever keep the one version around; though if you're finding yourself installing a lot of labelled toolchains (e.g. `nightly-2019-07-12` or `1.34.0`) then it'll be up to you to `rustup toolchain uninstall` them.

Rather than a cleanup command per-se, it'd probably make more sense if we made it so that any files left in the `download` dir are deleted *iff* we complete a full update.

Does that sound good to you?

**Comment by timw4mail** [comment]
Yeah, that make sense, and sounds like a better plan than a manual cleanup command.

**Comment by BeniCheni** [comment]
Friendly note: trying out a branch for this issue.
