### ISSUE TITLE
FYI: fish completions level up

### ISSUE THREAD

**Issue by mqudsi** [rust-lang/rustup#2069]
Hi team,

Just wanted to let you know that the next version of fish (also available in current nightly builds) will feature `rustup` completions on steroids out-of-the-box. Unlike most other shells, fish completions are dynamic and interactive, and react in real-time to changes at the command line, and complete not only the name of options but their values, too.

I had to hardcode a few things I'd have rather not (workarounds welcome!), but the non-machine-generated `rustup` fish completions can be seen here: https://github.com/fish-shell/fish-shell/blob/master/share/completions/rustup.fish

What that means is fish's rustup completions are aware of what components and toolchains are installed and can intelligently offer suggestions based off your current rustup state and what you've already entered at the command line.

Here's a demo of it at work: https://asciinema.org/a/ZocGT2sMY3EHNVmUTUs9M2562

Enjoy!

**Comment by kinnison** [comment]
Rustup can generate completions to some extent itself (`rustup completions fish`) though that doesn't include targets because they're dynamic based on which toolchain you're thinking about and would need quite complex completions rules which I'm not sure if clap can do (yet)

If there's anything useful we can do for you on the `rustup` side to improve integration, please let me know, otherwise I'm not really sure this needs to stay open so I'm going to close it :D

Thanks again.
