### ISSUE TITLE
rustup-init.sh does not correctly detect host string for Pinebook Pro

### ISSUE THREAD

**Issue by NoraCodes** [rust-lang/rustup#2111]
**Problem**
On Pinebook Pro Debian stretch (9.9), `rustup-init.sh` tries to download `rustup-init` for `aarch64`, but that doesn't work; the CPU is ARMv8. Even once I downloaded an `armv7` `rustup-init`, it guessed the wrong target triple.

**Possible Solution(s)**
Instead of just checking `uname`, check the actual `ld` library; on my machine this is only `ld-linux-armhf.so.3` and therefore it is detectable that any `aarch64` binaries won't run.

**Comment by kinnison** [comment]
Can you please confirm the output of `uname -s`, `uname -m` and `dpkg --print-architecture` ?

**Comment by NoraCodes** [comment]
`uname -s`: `Linux`
`uname -m`: `aarch64`
`dpkg --print-architecture`: `armhf`

**Comment by kinnison** [comment]
Okay, that's fascinating.  I suppose it might be similar to someone running an `amd64` kernel and a 32 bit userland, but without running it under a 32 bit personality.  Hmm.

Perhaps we could add a check via `getconf LONG_BIT` which should return `32` for you (if you can confirm?)

**Comment by NoraCodes** [comment]
LONG_BIT does indeed report 32, yeah.

**Comment by tesuji** [comment]
But is `getconf` portable enough?

**Comment by kinnison** [comment]
I'd only be suggesting the use of `getconf` when diagnosing a linux system which reports `amd64` or `aarch64` since those are the natively bi-arch options I think.  Others need personality switches IIRC
So it'd be a disambiguation step, not something run everywhere.  As for where it comes from -- on Debian it's in `libc-bin` so I'm guessing it's part of the set of things glibc tends to have.  No idea if musl would have it, but we could simply say that if `getconf` can't run, we assume same bitness as the kernel personality reported.

**Comment by kinnison** [comment]
@NoraCodes Short term fix for you would be to download `rustup-init.sh` and then run it with: `linux32 sh rustup-init.sh` -- that should get you the right rustup etc.

**Comment by NoraCodes** [comment]
Thank you, that worked well.

**Comment by kinnison** [comment]
Okay cool, so @NoraCodes can at least get on with Rust on her Pinebook, and I have an idea for how we might resolve this for future users.

**Comment by kinnison** [comment]
If anyone wishes to approach this, please let me know here, or via Discord in the `#wg-rustup` channel.

**Comment by kinnison** [comment]
@NoraCodes Could you please try https://raw.githubusercontent.com/kinnison/rustup.rs/kinnison/32bit-linux-on-64bit-kernel/rustup-init.sh which contains the little fix I think we need for this?  All you need do is download it, and run it and see if it fetches the right installer.  If it doesn't, please run it `sh -x rustup-init.sh` look for where it starts to inspect `/proc/self/exe` and copy/paste from there to where it starts downloading the installer, so that I can diagnose better.

**Comment by NoraCodes** [comment]
I am away from my PBP at the moment but I will do this tomorrow. Thanks for the prompt attention!

**Comment by NoraCodes** [comment]
Sorry that "tomorrow" became Wednesday :/

In any case, I get an error that `https://static.rust-lang.org/rustup/dist/armv7-unknown-linux-gnu/rustup-init` is 404ing, but that looks like the right decision to download!

**Comment by kinnison** [comment]
@NoraCodes Hmm, 404 seems odd, but we're getting somewhere (It's wanting to change its decision a bit) I'll have a rummage and see what I've missed...

`<fx: time-passes>`

I've pushed a fix to that branch, I wasn't taking into account the fact that armv7 non-android has an ABI suffix.  Could you give that same link a fresh go?  If it works then we're sorted.

**Comment by NoraCodes** [comment]
Works perfectly, thank you!

**Comment by kinnison** [comment]
Fabulous, thank you for the testing.  I shall file a PR soon.
