### ISSUE TITLE
Requires >500Mb of memory to install rustc

### ISSUE THREAD

**Issue by teknopaul** [rust-lang/rustup#2145]
**Describe the problem you are trying to solve**
I was trying to install rustc on a nano micro VM with only 500Mb of RAM, the installer runs out of memory, if I install on a machine with more RAM and rsync the files using rustc works well .

**Describe the solution you'd like**
Either working in low mem environments or publish the minimum system requirements.  Currently it just crashes without reporting the cause.

I still have this VM so let me know if I can do anything to help testing the issue.

**Comment by kinnison** [comment]
This is related to a conversation we had here: https://github.com/rust-lang/rustup/issues/2128#issuecomment-554730037

We would need a way to detect the available RAM limits in a clean way to automate this; otherwise users of deliberately limited VMs need to set `RUSTUP_UNPACK_RAM` to something suitable in their profile.

**Comment by rbtcollins** [comment]
Also, its worth looking at things like this -
https://internals.rust-lang.org/t/rustc-build-memory-requirement/7457 -
there's little point having the installer be radically better than the
compiler.

I recall a longer conversation back on the PR that merged the parallel
unpacking install code around this as well.

One thing we could do in principle is handle out of RAM situations better,
but sadly rust largely treats malloc failures as fatal rather than a
handlable error, without some serious voodoo I'm not familiar enough with
to work on yet.

-Rob

**Comment by hanusek** [comment]
I have the same problem - a embedded device with 256 MB RAM. How to solve it?

**Comment by rbtcollins** [comment]
Start by setting RUSTUP_UNPACK_RAM=128000000 or something like that.

-Rob

**Comment by teknopaul** [comment]
I managed to install on a machine with more ram and copy the files across.

**Comment by daveorzach** [comment]
I successfully installed rustc after adjusting the unpick size
`export RUSTUP_UNPACK_RAM=200000000`

**Comment by kaleidawave** [comment]
> I successfully installed rustc after adjusting the unpick size
> `export RUSTUP_UNPACK_RAM=200000000`

Haven't managed to get this working. Fails with `thread 'main' panicked at 'RUSTUP_UNPACK_RAM must be larger than 220000000', src/dist/component/package.rs:200:13`

And still 220mb is too large for my environment... so it seems there is no way to install rustc...?

**Comment by kinnison** [comment]
We are working toward making it more possible, but frankly if you're not able to give up 220M to install rust, you're not going to be able to build very complex programs.

**Comment by rbtcollins** [comment]
Fixed by #2707
