### ISSUE TITLE
build: Remove 32-bit Apple build

### ISSUE THREAD

**Issue by tesuji** [rust-lang/rustup#2180]
Soon with https://github.com/rust-lang/rust/issues/67724 we may also want to remove
i686 Apple build.

**Comment by kinnison** [comment]
I would argue that removing the build is relevant but not until 1.42.0 is released which demotes that platform to tier 3.  There's then the issue of what happens to people with a 32bit build of rustup installed at the point they do `rustup self update` and we're not longer releasing that target -- we might want to ensure the error messages are pleasant in that context rather than just unfortunate -- or even disable self-update for that target in a release before finally removing support in another release.

**Comment by kinnison** [comment]
When I migrated us to github actions I just didn't include i686 apple, so this is actually done.
