### ISSUE TITLE
Question/clarification: "tool `*` is already installed... to have rustup manage this tool" OR "info: rolling back changes"

### ISSUE THREAD

**Issue by cheako** [rust-lang/rustup#2224]
Problem A: https://gitlab.com/cheako/websuite-rs/-/jobs/425803007#L255
Possible symptom: https://gitlab.com/cheako/websuite-rs/-/jobs/425803007#L266
I don't know if this is my issue, but it seems likely that this mechanism is responsible for my other plight.  What's responsible for this "already installed" message?  I'd like to know what file of files are corrupted to get this effect.  That's why I tried the strace, to see what file might not be being cached or is getting corrupted, but came up empty.  If you'd be so kind as to point out what file(s) contain the data used to determine a "info: rolling back changes" that would be helpful.

Both fmt and clippy should be part of rustdocker/rust:stable, so I'm not sure if I should be getting this error or not.

What's unique about this installation is the caching strategy.
https://gitlab.com/cheako/websuite-rs/-/blob/7549ced1565df4aa5c82b44d2fea2db4dac5c759/cache-begin.sh
https://gitlab.com/cheako/websuite-rs/-/blob/7549ced1565df4aa5c82b44d2fea2db4dac5c759/cache-trim.sh
I wrote these a while ago and this is the first problem.  The diff in cache-trim do exactly what one would suspect, remove files that are the same in both places, ignoring files that only exist in one.  In cache-begin we overwrite new files, because zip is used file times are lost so that's why perl is used to save/restore them.  This could train wreck, but gitlab has a handy delete cache files button so it's not a concern.  Though this cache file is brand new the same day as the A failure, the other has been a continual eye sore but nothing more.

**Comment by rbtcollins** [comment]
info: rolling back changes is output when rustup has encountered an error, its part of the 'transactional' handling (narrator, it is neither ACID nor BASE) of updates.

A bit of background will help understanding things here. rustup provides proxies for all the rust executables, which act as thunks to the toolchain specific versions. When rustup is updated, which happens from line 266, those proxies get removed and replaced. The message about 'tool is already installed' is a warning because sometimes folk manually install e.g. rls in `~/.cargo/bin` before it becomes part of rust, and then when rustup starts offering the proxy the binary already exists, and we're conservative about replacing it. But we don't treat this as an error for some historical decision I'm not aware of.

There will be an underlying error reported as well, lets see, yes line 255:
```
error: failed to install component: 'rust-std-wasm32-wasi', detected conflict: '"lib/rustlib/wasm32-wasi/lib/libstd-c3ac5936692b63da.rlib"'
```

rustup just uses the existence of the target directory to determine if a toolchain is installed.

It looks like rustup may be running twice, as it seems to be running at the top before your cache-begin call is made. rustup isn't concurrent-invocation safe presently.

**Comment by rbtcollins** [comment]
So yeah, I'm pretty sure this is effectively a variation on "running rustup twice at once breaks", where the second invocation happens to be spelt rsync.

**Comment by cheako** [comment]
That's easy to explain away.  Still wanting to know what causes the error, where is rustup reading something or encountering an error(even if it is another instance of rustup there should be a point where they collide)?

Where is the other invocation of rustup?  This is a CI command https://gitlab.com/cheako/websuite-rs/-/blob/7549ced1565df4aa5c82b44d2fea2db4dac5c759/.gitlab-ci.yml#L15 nothing else should be running.

I think the information on rustup using the existence of a directory is incorrect.  strace would have logged any test for directory existence or attempt to access a directory and I don't see any.

**Comment by cheako** [comment]
Are you indicating that the rustdocker/rust:stable have manually installed these?  I don't think that's likely.  I'm asking how rustup knows these have been manually installed.

**Comment by cheako** [comment]
Through testing I've determined that settings.toml and toolchains/*/lib/rustlib/multirust-channel-manifest.toml are likely culprits.  I'm looking closer at how these files are changed at various stages.  Testing of this issue is made difficult due to everything being gitlab CI.

**Comment by cheako** [comment]
https://gitlab.com/cheako/websuite-rs/-/jobs/427194762
Lines 23 to 49 show the initial state, pre and post rsync.  42 - 44 is installing target for service worker.  60 to 63 shows the files are unchanged??!

**Comment by rbtcollins** [comment]
Hmm, ok, so not concurrent invocation. But.

Here was what I saw:  one invocation of rustup in the gitlab ci yaml file; but in the console output at line 25:
```
 info: syncing channel updates for '1.41.0-x86_64-unknown-linux-gnu'
  1.41.0-x86_64-unknown-linux-gnu unchanged - rustc 1.41.0 (5e1a79984 2020-01-27)
info: checking for self-updates
rustup 1.21.1 (7832b2ebe 2019-12-20)
rustc 1.41.0 (5e1a79984 2020-01-27)
cargo 1.41.0 (626f0f40e 2019-12-03)
$ ./cache-begin.sh
```

and the second at the end reporting its completion at line 269:
```
 rustup 1.21.1 (7832b2ebe 2019-12-20)
rustc 1.41.0 (5e1a79984 2020-01-27)
cargo 1.41.0 (626f0f40e 2019-12-03)
```

But `rustup target add wasm32-wasi` should output this:
```
rustup target add wasm32-wasi
info: downloading component 'rust-std' for 'wasm32-wasi'
 11.3 MiB /  11.3 MiB (100 %) 889.2 KiB/s in  3s ETA:  0s
info: installing component 'rust-std' for 'wasm32-wasi'
```

That summary of installed components is from rustup-init and rustup update, from memory.

So, I am not in a position to say definitively what is happening, but it is consistent with something writing files into the toolchain dir while rustup runs and/or modifying metadata behind rustups back. Conflicts occur when rustup's manifest of installed files doesn't match what is installed, and rustup ends up trying to install a file that is already there. We don't currently take an eventually consistent approach (though that would be a thing we could do in future).

The warnings down the bottom about tools already installed are probably due to hard link breaking by your cache script: see the link count here:
```
-rwxr-xr-x 12 robertc robertc 12245112 Feb  3 08:31 cargo-fmt
```
There is an rsync option to preserve hard links, the data set is probably small enough that that won't be too slow. That would then leave us just the wasm32-wasi rollback issue.

**Comment by cheako** [comment]
I'll write perl scripts that will recreate any hard links, thanks for this information!  and change the rsync options of course.

/* Ignore this: What files need to be hardlinked?  As I indicated we are transitioning through a zip file, so any information about HL would need to be recreated. */

I don't think I need this either, if hard links are my issue.
Also when you say rustup's manifest, can you define that...  This is my exact question, what makes rustup think this is not installed when it is?  Obviously checking the manifest is an important FIRST step, but I'm askin how to do that!

That's why I traced files, because that would show any access to a manifest.

**Comment by rbtcollins** [comment]
the proxies are all hardlinked to rustup itself. Thats why the message shows up after the self update check.

We stat the toolchain dir to see if the toolchain is installed, as I said. For components, the component is listed in $RUSTUP_HOME/toolchains/$TOOLCHAIN/lib/rustlib/components if it has been installed.

**Comment by cheako** [comment]
I see, so implementing hard links will just fix the warnings about fmt.

This log doesn't show any access to toolchains itself.
https://gitlab.com/cheako/websuite-rs/-/jobs/425803007

On line 91 rustup just magically knows about 1.41.0-x86_64-unknown-linux-gnu, but nothing it accesses prior would indicate that exists.

The only meaningful access I see is to /root/.rustup/settings.toml, but this file dosn't contain 1.41.0-x86_64-unknown-linux-gnu AFAICT.

**Comment by rbtcollins** [comment]
Implementing the hardlinks will make sure that when we change code in the proxies rustup installs new proxies : right now its not touching the files it is warning about when invoked by the cargo command a few lines up in the log. 

This is how we determine installed toolchains:
```
pub fn list_toolchains(&self) -> Result<Vec<String>> {
        if utils::is_directory(&self.toolchains_dir) {
            let mut toolchains: Vec<_> = utils::read_dir("toolchains", &self.toolchains_dir)?
                .filter_map(io::Result::ok)
                .filter(|e| e.file_type().map(|f| !f.is_file()).unwrap_or(false))
                .filter_map(|e| e.file_name().into_string().ok())
                .collect();

            utils::toolchain_sort(&mut toolchains);

            Ok(toolchains)
        } else {
            Ok(Vec::new())
        }
    }
```

I suspect -etrace=file is not including readdir. You're installing a component, not a toolchain, which is why a single stat of the toolchain dir isn't being made; different codepath is being hit.

**Comment by cheako** [comment]
Thanks for the loads of help, I appreciate it as I know I'd be stuck without it.  I think this has todo with the processing of diff output incorrectly identifying ```components``` as unmodified.

https://gitlab.com/cheako/websuite-rs/-/jobs/425803007#L100

**Comment by rbtcollins** [comment]
Well it is opening components, finding the wasm bits aren't listed there,
then downloading and installing them, but when it goes to write them to
disk, they are present.

Perhaps they are already on disk before your cache restore? Does your cache
restore delete files that are already on the worker but not present in your
cache? If not then this would also explain the problem, because you're
replacing the `components` file with one with lesser contents, but the base
image has more components already installed?

**Comment by cheako** [comment]
Because the trim script removes components from the cache, the begin script copies the components file from the image into the directory to the cache.  This is because the output of diff, it's supposed to remove duplicate files from the cache, isn't being processed correctly.
