### ISSUE TITLE
rustup force skips components by default

### ISSUE THREAD

**Issue by vext01** [rust-lang/rustup#2227]
**Problem**

When installing a nightly, my understanding is that rustup should walk back in time, installing the first snapshot with all of the requested components. However, today it seems not.

https://blog.rust-lang.org/2019/10/15/Rustup-1.20.0.html

> Starting from rustup 1.20.0, if a component you previously installed is missing in the latest nightly, rustup update will walk backwards in time to find the most recent release with all the components you need.

**Steps**

1. At a time when there are components missing (i.e. now), under a fresh user user account with no pre-existing `~/.rustup` or `~/.cargo`, copy+paste the rustup install shell snippet to run the installer: `curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh`
2. Install the latest nightly using the default profile.
3. Observe messages like:

```
warning: Force-skipping unavailable component 'clippy-x86_64-unknown-linux-gnu'
warning: Force-skipping unavailable component 'rustfmt-x86_64-unknown-linux-gnu'
```

Shouldn't rustup have walked back to find a nightly with all of the components?

Maybe I'm doing something wrong, but I can't see a way to install the last complete toolchain.

**Comment by kinnison** [comment]
This was a decision which was made because people wanted to be able to install immediately.  The initial install is always forced, as it any install which occurs automatically because of `rust-toolchain` or similar.  If you always want the backtracking support you should install `rustup` with `--default-toolchain none` and then do an explicit `rustup toolchain install nightly` which will enable backtracking mode.

**Comment by vext01** [comment]
That does indeed work, however I find that a very surprising behaviour.

Is this documented somewhere? If not, we should add docs.

**Comment by kinnison** [comment]
I don't think it is formally documented no.  I'm sad that you found it surprising since our goal was to reduce surprise (people were confused when `rustup-init` could fail).  If you have some suggested wording for an update to the README to help reduce the chance that others will be caught out like you were, I'd appreciate a PR.  You'd probably be best placed to know where you'd have looked for this and thus what and where the change would be best placed.

**Comment by elichai** [comment]
@kinnison I just found this after fighting with the installer trying to make it work with 
`curl https://build.travis-ci.org/files/rustup-init.sh -sSf | sh -s -- -y --default-toolchain nightly --profile minimal -c miri` my usecase is running Miri in the CI so all I care about is getting a compiler+miri fast. I guess I need to split it to 2 phases? (1 install rustup 2 install nightly?)

**Comment by kinnison** [comment]
In theory you should be able to install minimal with miri in that fashion.  In what way is that failing? Can you point me at a travis log?

**Comment by elichai** [comment]
> In theory you should be able to install minimal with miri in that fashion. In what way is that failing? Can you point me at a travis log?

https://travis-ci.org/elichai/rust-secp256k1/jobs/654451023#L199

I ended up doing:
```
curl --proto '=https' --tlsv1.2 https://build.travis-ci.org/files/rustup-init.sh -sSf | sh -s -- --default-toolchain none -y
rustup toolchain install nightly --allow-downgrade -c miri
```

**Comment by kinnison** [comment]
Aha, yes, that's true, miri isn't guaranteed, so you will need to do it that way.  If you feel up to it, perhaps a README section to suggest this approach would be a nice PR to offer us? :grin:
