### ISSUE TITLE
[fish] changing environment variables having no effect on rust

### ISSUE THREAD

**Issue by FraserEmbrey** [rust-lang/rustup#2270]
**Problem**
-> _Seems to be peculiar to fish shell_

I have set my `CARGO_HOME` and `RUSTUP_HOME` to be in the config folder to keep my home folder clean. Then called the install script. The script created both `~/.cargo` and `~/.rustup` and ignored my variables.

I then tried to move them and cargo failed to work telling me the toolchain wasn't installed.

I expected the same experience as with the default zsh. Rustup should put my files into the directories set by the environment variables. If the installer doesn't do that then I expect the environment variables to have an effect when rust is actually installed on the system.

I still get the error in zsh even though the installer installs cargo to where `CARGO_HOME` is set

**Steps**
1. Set environment variables RUSTUP_HOME and CARGO_HOME to folders other than default
2. Install rustup
3. Try to move folders to where the environment variables point to 
4. Use cargo run on a hello world program (for example)
5. Error

**Notes**

Output of `rustup --version`: `rustup 1.21.1 (7832b2ebe 2019-12-20)`
Output of `rustup show`:
```
Default host: x86_64-apple-darwin
rustup home:  /Users/frsr/.config/rust/rustup

stable-x86_64-apple-darwin (default)
rustc 1.42.0 (b8cedc004 2020-03-09)
```

**Comment by kinnison** [comment]
Given that the test suite relies on being able to set `RUSTUP_HOME` and `CARGO_HOME` and have things work, I fear this is specifically a `fish` problem rather than a `rustup` problem.

FYI the `.config` path (`XDG_CONFIG_DIR` presumably) isn't really where `.rustup` belongs since it contains both settings *and* toolchains.  If `rustup` were to obey XDG, we'd need to split the config into `.cache` and the toolchains into some libdir somewhere.

**Comment by bschwb** [comment]
@FraserEmbrey I had a similar issue, where cargo seemingly ignored the `CARGO_HOME` variable with fish as a shell. Turns out, that I didn't export the environment variable. Specifically I ran `set -U CARGO_HOME $HOME/somewhere/.cargo`, when instead it's important to also export the variable with the `-x` flag:  `set -U -x CARGO_HOME $HOME/somewhere/.cargo`.

To rule out similar issues, can you provide how you set the environment variables?

**Comment by FraserEmbrey** [comment]
Sorry for the delay in my reply. I have set the cargo home using `export` in fish and also in zsh. I am not sure why exactly but it seems to be working now.

I have not tried `set` with the `-x` flag. This may well have been the issue
