### ISSUE TITLE
Support tcsh

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rustup#2311]
**Describe the problem you are trying to solve**
The environment variable script in `~/.cargo/env` does not support tcsh.

**Describe the solution you'd like**
Either have two different scripts depending on the shell detected, or add 'compatibility' using something like https://superuser.com/a/373964/709183.

**Notes**
I'm fine if the shell isn't determined automatically as long as there's a way to select a different one.

I _can_ go in and edit the env file by hand, but it's annoying.

**Comment by workingjubilee** [comment]
Going to fix this as part of https://github.com/rust-lang/rustup/issues/2106#issuecomment-619702210, any further pointers you can provide on `tcsh` and how *BSD environments handle rcfiles and env vars is appreciated.

**Comment by kinnison** [comment]
I'm inclined to say "You chose to shoot yourself in the foot by using a *csh, you get to keep all the splattered bloody bone fragments" but if @workingjubilee wants to have a go at supporting them too then I won't stop them.

We'd need a `env.sh` and `env.csh` because they use fundamentally different syntaxes for controlling environment variables (`export` vs `setenv` for example).  If we're going to do this then we should probably also embrace the other popular non-POSIX shell out there and have an `env.fish` (blech)

**Comment by workingjubilee** [comment]
To be clear, I don't have the faintest of how fish works, aside from "surprisingly differently", so while I will probably engage a refactoring step that will make it easier to add stuff for the fish shell, I have no firm intention of making it work.

**Comment by jyn514** [comment]
@workingjubilee this is unrelated to BSD, you can install tcsh on any machine. In my case this was CentOS 8, but I've used it on ubuntu as well.

**Comment by jyn514** [comment]
I think this is a misfeature tbh.
