### ISSUE TITLE
rustup-init completion message issues

### ISSUE THREAD

**Issue by drguildo** [rust-lang/rustup#2334]
**Problem**

On completion, rustup-init prints:

![image](https://user-images.githubusercontent.com/9282/82148899-f430d980-984c-11ea-9d7d-449a0bd36760.png)

The line wrapping is a bit janky and also there is a backslash missing in the path `%USERPROFILE%.cargo\bin`, which should be `%USERPROFILE%\.cargo\bin`.

Output of `rustup --version`:

`rustup 1.21.1 (7832b2ebe 2019-12-20)`

Output of `rustup show`:

```
Default host: x86_64-pc-windows-msvc
rustup home:  C:\Users\Simon\.rustup

stable-x86_64-pc-windows-msvc (default)
rustc 1.43.1 (8d69840ab 2020-05-04)
```

**Comment by VladKou** [comment]
The missing "\" is an issue with the current stable release. It was fixed in https://github.com/rust-lang/rustup/commit/cac1d3a53f554ecacb9bf873ff21cea7c3c08f36

Building rustup from source, and running it shows the expected string:

![image](https://user-images.githubusercontent.com/3132093/82162638-f8fc8a00-985a-11ea-88c3-76d1392e8e34.png)
