### ISSUE TITLE
Create symlink to default toolchain

### ISSUE THREAD

**Issue by Janfel** [rust-lang/rustup#2356]
**Describe the problem you are trying to solve**

- I want to be able to use `man rustc` instead of `rustup man rustc` for consistency.
- I want the `bin` of the currently active toolchain on my `$PATH` because my distribution’s package doesn’t provide all necessary symlinks to `rustup` in `/usr/bin`.
- I want `rustup default` to change the binaries and man pages I access immediately without having to reload my shell.
- I do not want to run `rustc --print sysroot` in my `.zshrc`, as this slows down my shell startup and still requires a reload to be effective.

**Describe the solution you’d like**

Running `rustup default stable-x86_64-my-toolchain` should create a symlink like this:
```sh
ln -sfn stable-x86_64-my-toolchain $RUSTUP_HOME/toolchain/default
```
This allows me to add `.rustup/toolchain/default/bin` to my `$PATH`, providing the following benefits.

- I can run every installed binary of the default toolchain without relying on symlinks that might or might not exist for multiplexing.
- I can use `man rustc` as `man-db` automatically finds `.rustup/toolchain/default/share/man` from the entry in my `$PATH`.
- Running `rustup default` changes the binaries and man pages I access immediately.

**Notes**

- The Haskell toolchain manager [ghcup](https://gitlab.haskell.org/haskell/ghcup-hs) uses a mechanism similar to what I describe here.
- There might be a use case for further symlinks (`stable`, `nightly`, `stable-x86_64`), but this would require rustup to manage several “activated” toolchains at once and is likely not worth the effort.

**Comment by kinnison** [comment]
This would result in exceedingly confusing situations if the path were *before* the path containing rustup's proxies since things like `cargo +othertoolchain build` would cease to function, ditto `rust-toolchain` files or directory overrides.  If it came after then the binaries would be being proxied by `rustup` anyway, so the only thing you gain is `MANPATH` and even then, it wouldn't be honouring overrides etc and so would be surprising in silent ways in a number of cases.  I'd suggest just adding a prompt command to your shell config which acquired the path to the current toolchain and put it into the MANPATH instead if I were you.

**Comment by Janfel** [comment]
I wasn’t aware rustup has these features and I agree with your assessment.
