### ISSUE TITLE
rustc doesn't work with torsocks on

### ISSUE THREAD

**Issue by richdev135** [rust-lang/rustup#2364]
**Problem**
When torsocks is ON, rustc gives an error and does not complete.

**Expected**
rustc is uneffected by torsocks 

**Steps**
1. Ensure torsocks is not ON 
2. run `rustc -- version`  [notice version is shown]
3. run the command: `source torsocks on`
4. `run rustc --version` [you'll see the following error:
`1591298648 WARNING torsocks[3661]: [syscall] Unsupported syscall number 332. Denying the    call (in tsocks_syscall() at syscall.c:605)`
[and the command doesn't finish]

**Notes**
Output of `rustup --version`:
`rustc 1.44.0 (49cae5576 2020-06-01)`

Output of `rustup show`:
`error: couldn't read show: No such file or directory (os error 2)
error: aborting due to previous error`

OS: ubuntu 20.04
`NAME="Ubuntu"
VERSION="20.04 LTS (Focal Fossa)"`

**Comment by kinnison** [comment]
The syscall number is the `rseq()` call which suggests that 20.04's glibc is doing calls which torsocks doesn't support.  Since `rseq` does't show up in the rust-lang/rust repository as far as I can tell, it's not rust's fault per-se.

@rbtcollins do you agree, or have I missed something?

**Comment by rbtcollins** [comment]
https://github.com/rust-lang/rustup/issues/2289 shows torsocks errors too, but rustup installation seems to succeed.

https://trac.torproject.org/projects/tor/ticket/30658 suggests that 332 might be __x64_sys_statx and https://github.com/torvalds/linux/blob/master/arch/x86/entry/syscalls/syscall_64.tbl#L343 agrees.

So the problem here is indeed torsocks. @richdev135 I suggest you get bug 30658 in torsocks fixed, then rustup will work correctly.

**Comment by richdev135** [comment]
Gotcha... Makes sense. Thanks!

**Comment by mareng0** [comment]
Any idea when bug 30658 in torsocks gets fixed? I also get the error on Ubuntu 20.04. @richdev135

**Comment by rbtcollins** [comment]
Try asking on the torsocks bug tracker...

**Comment by oblitum** [comment]
It got fixed upstream, but as of 2022, there's no newer release yet.
