### ISSUE TITLE
rustup: unrecognized OS type: OpenBSD

### ISSUE THREAD

**Issue by plavcik** [rust-lang/rustup#2377]
```shell
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
rustup: unrecognized OS type: OpenBSD

OpenBSD 6.7 amd64
```

**Comment by kinnison** [comment]
Rustup is not (yet) available for OpenBSD.

**Comment by jtmoon79** [comment]
This still occurs for OpenBSD 7.2 on i386.
```lang-text
$ curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
rustup: unrecognized OS type: OpenBSD
```

Looking at the [Rust Reference for `target_os`](https://doc.rust-lang.org/reference/conditional-compilation.html#target_os), it includes value `"openbsd"`.

- Does anyone know how to install rust without `rustup`?
- Should this Issue be left open so to imply some day OpenBSD will be supported?

**Comment by rbtcollins** [comment]
OpenBSD is tier 3 per https://doc.rust-lang.org/nightly/rustc/platform-support.html#tier-3

We'll happily accept patches from people that want to make that work better. 

However it isn't up to rustup to get OpenBSD 'supported', since supported implies having the ability to CI test it, with official builds of the compiler and so on.

To answer your question, you can probably cross compile rust to OpenBSD, or perhaps someone has a ports build for it. If that works you could start work on porting rustup to OpenBSD.

I don't see much value in having bugs open on anything below tier 2, because even if fixed we can't CI check them or prevent regressions. So its more of a opensource in late 90's early 2000's era scratch-your-own-itch situation.

That said, if you're planning on working on this, then sure, lets have the bug open as a discussion mechanism, though finding us on discord might be better if you want get promptish feedback on questions.
