### ISSUE TITLE
reqwest download backend is lacking socks support

### ISSUE THREAD

**Issue by Sherlock-Holo** [rust-lang/rustup#2409]
**Problem**

**Steps**

1. run `https_proxy=socks5://127.0.0.1:1990 rustup update` and it doesn't use proxy because I watch `iftop -B` and nothing connect to my proxy server
2. use proxychians and see `iftop` it connects to my proxy server

**Comment by kinnison** [comment]
@inejge any ideas?

**Comment by inejge** [comment]
Support for `SOCKS` proxies in `reqwest` is behind the `socks` feature, which (AFAICS) isn't on by default, nor is it enabled in `download`'s `Cargo.toml`; `git blame` points to af3ba46. My testing of `env_proxy` shows that it passes `socks5://...` through.

**Comment by kinnison** [comment]
Okay, sounds like we need to turn that on again :D  Thanks.

**Comment by gaveen** [comment]
@kinnison I'd like to work on this since it's marked both 'easy' and 'mentor'. How can I get help on starting with it?

**Comment by kinnison** [comment]
@gaveen Firstly I suggest that you get a local socks proxy working so that you can confirm if requests are passing through it.  Set up the `https_proxy` variable in the manner suggested in the issue description; and then confirm that `RUSTUP_USE_CURL=1 rustup check` uses the proxy but that `rustup check` does not.  After that you'll need to fork and clone rustup; and look at what it'll take to turn on the socks support in reqwest.  Likely this will involve changing the `download/Cargo.toml` file to enable the requisite feature.

You can come onto the rust-lang discord and find me in `#wg-rustup` if you want more discussion, or else respond here.
