### ISSUE TITLE
rustup component add rust-analyzer-preview does not add rust-analyzer executable to ~/.cargo/bin

### ISSUE THREAD

**Issue by zoechi** [rust-lang/rustup#2411]
**Problem**

I can install rust-analyzer using `rustup component add rust-analyzer-preview` but it is not added to `~/.cargo/bin` like all other components (clippy, rustfmt, ...) and therefore not in the path and not executable.

**Steps**

1.
2.
3.

**Possible Solution(s)**

**Notes**

Output of `rustup --version`: `rustup 1.22.1 (b01adbbc3 2020-07-08)`
Output of `rustup show`:
```
Default host: x86_64-unknown-linux-gnu
rustup home:  /home/user/.rustup

installed toolchains
--------------------

stable-x86_64-unknown-linux-gnu
beta-x86_64-unknown-linux-gnu
nightly-2020-03-19-x86_64-unknown-linux-gnu
nightly-x86_64-unknown-linux-gnu (default)
1.37.0-x86_64-unknown-linux-gnu

installed targets for active toolchain
--------------------------------------

wasm32-unknown-unknown
x86_64-unknown-linux-gnu

active toolchain
----------------

nightly-x86_64-unknown-linux-gnu (default)
rustc 1.46.0-nightly (5db778aff 2020-07-09)
```

**Comment by kinnison** [comment]
This is the expected behaviour at this point. #2408 added the proxy but I'm considering if it ought to be in `TOOLS` or `DUP_TOOLS` because people have installed it via other means before now.  For now, as per people who have talked about it, you can run `rust-analyzer` via `rustup run nightly rust-analyzer` which you can always set up as a shell alias if you want, or a small shell script if you so desire.

**Comment by kinnison** [comment]
The next release of `rustup` will contain the proxy either way.

**Comment by zoechi** [comment]
I see.
Feel free to close.

**Comment by teor2345** [comment]
Note that this change was backed out in 1.23 because `rust-analyzer` isn't stable yet:
https://github.com/rust-lang/rustup/pull/2408#issuecomment-734899954

**Comment by jangid** [comment]
Now that the rust-analyzer is officially announced as default LS, will the binary be installed to default location in next release?

**Comment by Jasha10** [comment]
According to the rust-lang blog post from Sept 22, 2022, [rust-analyzer is now available via rustup](https://blog.rust-lang.org/2022/09/22/Rust-1.64.0.html#rust-analyzer-is-now-available-via-rustup).

The following works for me:
```text
$ rustup component add rust-analyzer
info: downloading component 'rust-analyzer'
info: installing component 'rust-analyzer'
$ rustup run stable rust-analyzer --version
rust-analyzer 1.64.0 (a55dd71 2022-09-19)
```

According to the blog post, "The next release of rustup will provide a built-in proxy so that running the executable `rust-analyzer` will launch the appropriate version."

**Comment by janos-r** [comment]
I love this, I also got it running on helix with a custom `rustup run stable rust-analyzer` command, but I am confused about the version.
Why does the --version show the version of rustc and not the version of the real rust-analyzer?

**Comment by lesleyrs** [comment]
@janos-r I actually didn't get `rustup run stable rust-analyzer` working in languages.toml, even though it works in terminal. Had to add it to PATH to make it work, what did you do?

**Comment by zackw** [comment]
@lesleyrs This wrapper script may help, put it in `$HOME/.local/bin` or some other directory on your PATH and chmod +x it:

```
#! /bin/sh
# as of 2022-11-22 rustup-installed rust-analyzer isn't available
# directly in $PATH
exec rustup run $(rustup show active-toolchain | cut -d' ' -f1) rust-analyzer
```

**Comment by pothos** [comment]
@zackw Nice tip! Only `"$@"` is missing at the end to work with `--version` or similar arguments.

My complete version of `~/.cargo/bin/rust-analyzer`:
```
#!/bin/bash
set -euo pipefail
exec rustup run "$(rustup show active-toolchain | cut -d' ' -f1)" rust-analyzer "$@"
```

**Comment by janos-r** [comment]
> @janos-r I actually didn't get `rustup run stable rust-analyzer` working in languages.toml, even though it works in terminal. Had to add it to PATH to make it work, what did you do?

```
[[language]]
name = "rust"
language-server = { command = "rustup", args = ["run", "stable", "rust-analyzer"] }
```
Works like a charm. Sry I didnt see your message sooner. In the next release it should be part of the path automatically already tho. This above is just temporarily necessary before that.

**Comment by lesleyrs** [comment]
@janos-r Ok I found out why it wasn't working without path, I used that same line but in helix directory languages.toml not the user directory one. I guess you have to recompile to change the former? Thanks :D

**Comment by cbiffle** [comment]
So, one of the things that's valuable about the proxies in a well-defined (and PATH-exposed) location is that they take advantage of rustup honoring the `rust-toolchain.toml` file. By hardcoding `rustup run stable rust-analyzer` into editor configs, aren't we just running "whatever the current stable on this machine is", rather than the version pinned by the project?

Is there a good workaround for this other than the shell script someone posted above?

**Comment by zackw** [comment]
Maybe we could get `rustup run default ...` added? I was surprised to find that that doesn't already work.

**Comment by cbiffle** [comment]
FWIW this became relevant to me rather suddenly when `rls` was replaced by an imposter, but `rust-analyzer isn't ready yet (in the sense of having a rustup proxy that respects pinned toolchain versions)

**Comment by jjant** [comment]
Will we eventually get this working out of the box?

**Comment by lunasophia** [comment]
I don't think it's appropriate for this bug to be closed when the feature it requests is accepted but not yet delivered.

**Comment by rbtcollins** [comment]
@lunasophia what do you mean? Rustup-init installs a rust-analyzer proxy in current versions.

If you've installed the rust-analyzer component, it should just work. So the feature is delivered.

If you've got specific failures or errors, please file a new bug. I'm locking this now, since we're getting noise, and the appropriate thing to do is to file a new bug, not resurrect a closed, fixed, bug.
