### ISSUE TITLE
Install script does not exit with non-zero status code on failure.

### ISSUE THREAD

**Issue by rkxx08** [rust-lang/rustup#2439]
**Describe the problem you are trying to solve**
The install script invoked by this command `curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh` does not exit with non-zero status code on failure. It's hard to detect failure partial success or complete success at this point. This makes putting this command in another automation harder.

**Describe the solution you'd like**
Install script exits with non-zero status code on any error. 

**Notes**
I'm using the script in automated mode like this.

    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- --default-toolchain none --no-modify-path -y; exit $?

This always exits with `0`. I tested this with no network connection and script fails with `curl: (6) Could not resolve host: sh.rustup.rs` error but exit code is still `0`.

**Comment by kinnison** [comment]
Oh my this is not good IMO.  I think this is a bug rather than an enhancement request.

**Comment by rkxx08** [comment]
IMO, if we run `rustup` at the end, and if it fails, we can report its exit code as final exit code. But can we regard just an execution of `rustup` as successful installation?

**Comment by kinnison** [comment]
The issue as described is that our exit pathway for no network access is failing to return the error code properly.  It's possible to install rustup and then not have it on-path and for that to be deliberate so we can't just try to execvp `rustup` afterwards.

**Comment by danpls** [comment]
Actually the install script does return a non-zero status code if it fails.
We can easily test this by *unsetting* the `PATH` environment variable before running the script, forcing it to not find any of the binaries needed:
```sh
> (echo "unset PATH"; curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs) | sh; echo $?
rustup: need 'curl or wget' (command not found)
1
```
The cause of OP's problem was, that he ran the command without a network connection, so `curl` failed to even get the script from https://sh.rustup.rs, and thus exited with an error code having *written nothing to stdin*.
And at the other end of the pipe `sh` notices that **stdin was closed**, thus exiting with the status code of the previous command or in this case `0` as there was no previous command.

Fixing this problem is actually quite simple. We can detect if `curl` fails to retrieve the install script and instead write something to `stdin` which forces `sh` to exit with an error code.
E.g.:
```sh
(curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs || echo exit 1) | sh
```

So I am not sure if this still is an issue we need to fix, but if you do think so I'd be happy to replace all occurrences of the old command with this *"fixed" one* and submit a PR.

**Comment by kinnison** [comment]
Nicely caught.  My gut feeling here is that there's no great value in changing the recommended command to be even more complex.  People already whine from time to time about the extra arguments to curl, let alone if we introduced a subshell and so on.

I'm going to close this and hope the issue stands as something people will find if they accidentally hit a similar situation.
