### ISSUE TITLE
Missing 'rust-docs' component for 'musl' toolchains

### ISSUE THREAD

**Issue by Logarithmus** [rust-lang/rustup#2510]
I'm not sure if I should create this issue in `rustup` repo or in `rust`.
**Problem**
When you install any `musl` toolchain, e. g. `x86_64-unknown-linux-musl`, `rust-docs` component doesn't install.
I've digged into the issue, and found out that for some reason `rust-docs` is missing for some triples, among them are `*-musl` ones. https://static.rust-lang.org/dist/channel-rust-stable.toml

**Steps**

1. rustup toolchain install stable-x86_64-unknown-linux-musl
2. rustup doc

**Possible Solution(s)**
Add tarballs for `*-musl` triples to the server.

**Notes**

Output of `rustup --version`:
```
rustup 1.22.1 (2020-07-28)
```
Output of `rustup show`:
```
Default host: x86_64-unknown-linux-musl
rustup home:  /home/artur/.rustup

stable-x86_64-unknown-linux-musl (default)
rustc 1.46.0 (04488afe3 2020-08-24)
```

**Comment by ehuss** [comment]
The docs are not available for non-tier1 platforms due to the overhead and CI time involved in building them.  This issue is tracked in https://github.com/rust-lang/rust/issues/69525.  It may be possible for the channel manifests to redirect most platforms to the linux docs (probably `x86_64-unknown-linux-gnu`).  As a workaround, you can download the docs from  `x86_64-unknown-linux-gnu`.

**Comment by ehuss** [comment]
Oh, BTW, the x86_64-unknown-linux-musl includes the rust-docs component in the beta channel (via https://github.com/rust-lang/rust/pull/74871) which should hit stable next week.

**Comment by kinnison** [comment]
Given Eric's response above, I'm going to close this issue.  Hopefully everyone is happy now.
