### ISSUE TITLE
mktemp: too few X's in template ‘rustup’

### ISSUE THREAD

**Issue by flier** [rust-lang/rustup#2553]
**Problem**

Installation scripts don't work on ubuntu 20

```bash
$ curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
mktemp: too few X's in template ‘rustup’
rustup: command failed: mktemp -d -t rustup
info: downloading installer
mkdir: cannot create directory ‘’: No such file or directory
rustup: command failed: mkdir -p

$lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04 LTS
Release:	20.04
Codename:	focal
```

**Steps**

```bash
$mktemp -d -t rustup
mktemp: too few X's in template ‘rustup’

$type -a mktemp
mktemp is /usr/bin/mktemp
mktemp is /bin/mktemp
```

**Possible Solution(s)**

Create the temporary directory based on template `rustup-XXX`

**Comment by flier** [comment]
It is very strange that it cannot be reproduced on another ubuntu server instance.

**Comment by xinbin1122** [comment]
I have the same problem.

**Comment by kinnison** [comment]
What's odd is that seeing this error implies that `mktemp -d` failed for you.  The 'bad' template has been present in `rustup-init.sh` since 2016 it seems.  It *is* nominally a bug though so I'm reopening this.

The line in question is https://github.com/rust-lang/rustup/blob/master/rustup-init.sh#L75 and it should be pretty simple to add a `-XXXX` or similar on the end of the template string.

**Comment by icodeface** [comment]
got same error when `$TMPDIR` set to an invalid path, hopefully this can help other people.
