### ISSUE TITLE
Setting to only check for a self-update during `rustup update`

### ISSUE THREAD

**Issue by Nemo157** [rust-lang/rustup#2576]
**Describe the problem you are trying to solve**
When testing the staging rustup release I had it "upgrade" back to the previous version when I ran `rustup update nightly`. This made me reconsider somehow aliasing in `rustup update` to include `--no-self-update` so that I could control when rustup itself updates.

**Describe the solution you'd like**
Something like `rustup set update-self-update check-only` that will check whether a self-update is available and report it, rather than installing it straight away.

**Notes**

**Comment by Nemo157** [comment]
(I just noticed that `rustup toolchain install` also does a self-update, so `update-self-update` is probably a bad setting name, not sure what it could be called).

**Comment by kinnison** [comment]
Such a setting could be very useful, it'd be nice to clean up a bunch of `--no-self-update` in our test suite for example.  While not trivial, it shouldn't be too hard to add the setting and pipe it through to the requisite places in the CLI through our `Cfg` object.

**Comment by 0xPoe** [comment]
@kinnison  Can I working on this?

**Comment by kinnison** [comment]
Sure you're welcome to work on it.  Do you want to start by reading through how settings are passed around in the Cfg code, and then write a comment here with how you suggest you'll fix this?

**Comment by 0xPoe** [comment]
> Sure you're welcome to work on it. Do you want to start by reading through how settings are passed around in the Cfg code, and then write a comment here with how you suggest you'll fix this?

I will write my thoughts here after I read the code and go back to the code after you give your comments.

**Comment by 0xPoe** [comment]
Sorry for the late reply.

I have read the code and I think the problem can be solved in a few steps.
1. We need to add a self-update related setting item in Settings.
2. We need to set the value in Cfg with the set subcommand support.
3. Since the configuration can be read in Cfg, we can get the value from the cli (similar to get_default_host_triple) and check for it in the self-update mod and use it.

Do you think there is any problem?
Are there any other suggestions about this configuration item and its value name? @kinnison

**Comment by 0xPoe** [comment]
@kinnison ping~

**Comment by kinnison** [comment]
Sorry for the delay, I had a very busy work week.

I think your proposed approach is on-track.  I'd suggest a setting name along the lines of `auto-self-update` with permitted values `enabled` (default if missing), `disabled` (does nothing unless manually running `rustup self update`), and `check-only` (which does a check for new versions to report when otherwise it would do an automatic self update).

@Nemo157 Would that solve your use-case?

**Comment by Nemo157** [comment]
Yep, that seems about what I was thinking.

**Comment by 0xPoe** [comment]
Sorry, I forgot about this. I will take the time to add that feature recently.
cc: @jonhoo

**Comment by jonhoo** [comment]
@hi-rustin That would be amazing!
