### ISSUE TITLE
[Usage problem] How to download the source code of external deps of rust std

### ISSUE THREAD

**Issue by Gnosnay** [rust-lang/rustup#2644]
Hey there, thanks a lot for reading this issue. 
I am one novice of rust. When I learn the rust, I found one problem that I can not navigate into the external deps of rust std code.

## what is the problem

for example, I wanna know how `Hashmap` implemented. So I use Clion to read the source code std lib. And I found the std relies on the external dep called `hashbrown`, which I couldn't navigate into it to read more:
![image](https://user-images.githubusercontent.com/20450379/105638855-0f5de980-5eb0-11eb-91d4-32763e1cf0eb.png)

## what I found

I found the deps that std relies on are imported in the way called `rustlib` which are all stored under `.rustup`:

![image](https://user-images.githubusercontent.com/20450379/105638946-85fae700-5eb0-11eb-805a-d7785489fc80.png)

## what I wanna know

So, what I wanna know is that is there any way to use rustup to download the source code of `rlib` or make it possible to read the source code of deps of std lib?

I would appreciate it if anyone can offer the help. Thanks a lot for your reading.

**Comment by ehuss** [comment]
The source for dependencies is not available.  We attempted to add them to the rust-src component in https://github.com/rust-lang/rust/pull/78790, but it had to be reverted due to some issues it caused.  You can follow issue https://github.com/rust-lang/wg-cargo-std-aware/issues/23 for tracking adding it back.
