### ISSUE TITLE
Error while trying to cross-compiling in GitHub Action's VM.

### ISSUE THREAD

**Issue by yikerman** [rust-lang/rustup#2645]
**Problem**

I am trying to cross-compile the [Shadowsocks](https://github.com/shadowsocks/shadowsocks-rust) in both targets `x86_64-apple-darwin` and `aarch64-apple-darwin` in a GitHub Action. The workflow file can be found [here](https://github.com/xiaoyu2006/ss-buildbot/blob/d3502101b018da1133315c2e90f8c62cbc2dd4a2/.github/workflows/nightly.yml). It builds on my local machine, but [fails](https://github.com/xiaoyu2006/ss-buildbot/runs/1762069309?check_suite_focus=true) in the workflow.

**Possible Solution(s)**

Not sure if this is a bug of Rustup, GitHub Action VM or myself.

**Comment by ehuss** [comment]
Per the output:

```
info: downloading component 'rust-std' for 'aarch64-apple-darwin'
info: installing component 'rust-std' for 'aarch64-apple-darwin'
info: using up to 500.0 MiB of RAM to unpack components
info: syncing channel updates for 'stable-x86_64-apple-darwin'
info: checking for self-updates
```

It is installing the target for the stable toolchain.  But then it cd's into `shadowsocks-rust` to run the build which has a `rust-toolchain` which builds it for nightly.

You'll need to install the targets for the appropriate nightly release.

Also, FYI, installing rustup shouldn't be necessary, since it is installed in GHA already.  It is also updating the stable toolchain, but then not using it.

**Comment by yikerman** [comment]
Gotcha. Thanks.
