### ISSUE TITLE
Rustup latest version number!!!

### ISSUE THREAD

**Issue by Arian94** [rust-lang/rustup#2682]
https://github.com/rust-lang/www.rust-lang.org/issues/1459#issue-816783303
**Problem**
I'm sending what I've said in the issue above (in the link) again here.

 entered this command:
```rustup -V```
gave me this:
```rustup 1.50```
for some reason, i had to downgrade to version 1.31. so ran this:
```rustup install 1.31```
then re-entered ```rustup -V``` but instead of showing me 1,31, showed this:
```rustup 1.23.1```
Again ran rustup install 1.50 command to go back to my current version
it says it has installed 1.50 but when I enter ```rustup -V``` it gives me this:
```rustup 1.23.1```
did everything, nothing worked. so fuck it. what's wrong with it???????????????????????????
i couldn't find any place in your websites where you've exactly mentioned the latest version number. That's so silly.

**Comment by kinnison** [comment]
Hi,

It sounds like you're confusing versions of `rustup` with versions of **Rust**.

Rustup is the _installer_ where you seem to be more worried about **Rust** toolchain versions.

`1.50.0` is the current Rust version, and `1.23.1` is the current installer version.

If you can explain what it is you're trying to *achieve* then I can try and make some suggestions as to what you might need to run to make that happen.

**Comment by Arian94** [comment]
I know what you mean. But I just remember the very first time I entered the command ``` rustup -V``` it showed me a 'one' line result. But the next times I entered it, it showed 'three' lines of response being the first line as ``` rustup 1.23.1 ```. The next two are about the Rust versions and so on.
So, I supposed, something is wrong.

Besides, if there was just one place in the internet for the list of rustup versions, I definitely would've known that I've got the latest version of it. I couldn't find that list anywhere.

**Comment by kinnison** [comment]
The extended output of `rustup -V` explains itself quite clearly.  The first line is the version of `rustup` but since a lot of people were confused that they had `rustup 1.22.1` when they thought they had a Rust version of say `1.45.0` we added the additional lines to explain the active version of `rustc` as well.

If you want to know if you have the latest `rustup` you can simply run `rustup self update` and either it'll tell you you are up-to-date or it'll update `rustup` to the latest version.  This is independent of updating toolchains, though `rustup` will also self-update at the end of any `rustup update` sequence which updates all toolchains *and* rustup.

I'm going to assume you don't have any particular problem with rustup, beyond a misunderstanding of the output of the version flag, so I'm going to close this issue.  Good luck, and I hope you continue to enjoy using Rust.

**Comment by rbtcollins** [comment]
We have changed the behaviour of rustup -V over time to make it clearer. However your experience was recently and that happened a long time ago. A much better explanation is that the first output you saw (`1.50`) wasn't from `rustup -V`, but from `rustc -V`.

Perhaps we should ask the rustc team to consider a more verbose version output too, given how close the name rustup and rustc are.

**Comment by Arian94** [comment]
> We have changed the behaviour of rustup -V over time to make it clearer. However your experience was recently and that happened a long time ago. A much better explanation is that the first output you saw (`1.50`) wasn't from `rustup -V`, but from `rustc -V`.
> 
> Perhaps we should ask the rustc team to consider a more verbose version output too, given how close the name rustup and rustc are.

"A much better explanation is that the first output you saw (1.50) wasn't from rustup -V, but from rustc -V."
That might be right.
