### ISSUE TITLE
How to install exact version with rust-init?

### ISSUE THREAD

**Issue by kuvaldini** [rust-lang/rustup#2882]
**Describe the problem you are trying to solve**
Hello.
I need to install Rust with exact version, not latest. How is it possible?

**Describe the solution you'd like**
I'd expect/suggest to add version to URL, like:
`curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs/?version=1.24 | sh`

**Comment by kinnison** [comment]
We only permit the installation of the latest version of `rustup` using the init script.  If you wish to install a particular version of rustup for some reason, you'd need to construct an appropriate url directly and download it.

If you mean to install a particular version of the Rust toolchain though, then you can specify the default toolchain with a command like:

```console
$ curl --proto '=https' --tls1.2 -sSf https://sh.rustup.rs/ | sh -s --default-toolchain=1.54.0
```

But if you're using the installer interactively (which you are if you're not passing `-y` anyway) then you can just select a particular version of the toolchain instead of `stable` by selecting the relevant option in the installer menu.

Is that clear enough?

**Comment by kuvaldini** [comment]
Thank you

**Comment by ltfschoen** [comment]
this worked for me `curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs/ | sh -s -- --default-toolchain=1.68.0 -y`
i had to use `tlsv1.2` instead of just `tls1.2`
