### ISSUE TITLE
Need better error when trying to install with low disk space

### ISSUE THREAD

**Issue by ChrisGreenaway** [rust-lang/rustup#2937]
### Problem

I tried to install Rust when disk space was low and got the following error:

```error: component download failed for cargo-x86_64-unknown-linux-gnu: could not download file from 'https://static.rust-lang.org/dist/2022-01-20/cargo-1.58.1-x86_64-unknown-linux-gnu.tar.xz' to '/root/.rustup/downloads/1d3f01b973ea3de5174d0a48b50828cf913bafc223ecbf768a0293602cff0cdc.partial'```

which led me look for networking problems.

I would expect the error to indicate that the download could not be done due to limited disk space.

### Steps

1. Use an x86-64 Linux
2. Fill up your disk
3. Run the Rust installer with default options

### Rustup version

```console
Rustup was not installed when the error happened, but now that I made some disk space and re-ran the installer, the version is reported as:

rustup 1.24.3 (ce5817a94 2021-05-31)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.58.1 (db9d1b20b 2022-01-20)`
```

### Installed toolchains

```console
Default host: x86_64-unknown-linux-gnu
rustup home:  /home/user/.rustup

stable-x86_64-unknown-linux-gnu (default)
rustc 1.58.1 (db9d1b20b 2022-01-20)
```

**Comment by kinnison** [comment]
I agree we might be able to do better.  If you, or anyone else, want to have a go at a patch, I'd be happy to help.

**Comment by gautamprikshit1** [comment]
I can do it by adding sysinfo crate to the dependencies.

**Comment by ongchi** [comment]
This should raise `std::io::Error` with kind of `StorageFull`, but rustup only show one error rather then every error in cause chain, which caused only `RustupError::DownloadingFile` to be shown.

https://github.com/rust-lang/rustup/blob/87fa15d13e3778733d5d66058e5de4309c27317b/src/cli/common.rs#L652-L663

To fix this issue, the error message could be improved by printing every cause chain of error object or casting it into `RustupError::IOError`.

https://github.com/rust-lang/rustup/blob/87fa15d13e3778733d5d66058e5de4309c27317b/src/utils/utils.rs#L150-L175

Besides of that, I was suprised by functions in download crate not always returning `DownloadError` as error type, it's actually an error wrapped by `anyhow::Error`.
When IO error occurs, instead of forward to `DownloadError::IoError`, it will be wrapped by `anyhow::Error` with a context.
Because of this, in the function `download_file_with_resume`, your'll never catch an IO error when downcast to `DownloadError` unless downcast it to `std::io::Error`.
The `IoError` variant in `DownloadError` is really confusing.
