### ISSUE TITLE
rustup update gives error: rustup is not installed on Windows

### ISSUE THREAD

**Issue by CrommVardek** [rust-lang/rustup#2946]
### Problem

I've installed rust using the rustup-init.exe (x64) for Windows (10). After running `rustup update` I got an error (error: rustup is not installed at CARGO_BIN_PATH)

So far so good. I've added the following to path : %CARGO_HOME%/bin 

I can see it by running `echo $Env:PATH` (.cargo\bin;)

I then run the following command : 

`rustup default stable`

Everything is good.

Then I run `rustup update` 

and then I get the following output: 

`info: syncing channel updates for 'stable-x86_64-pc-windows-msvc'
error: rustup is not installed at 'C:\Users\MyUserName\.cargo\bin'`

### Steps

1.  install rust using the rustup-init.exe (x64) on Windows (10)
2. I've added the following to path : %CARGO_HOME%/bin 
3. I can see it by running `echo $Env:PATH` (.cargo\bin;)
4. Run `rustup default stable` (no issue)run `rustup update` 

and then I get the following output: 

`info: syncing channel updates for 'stable-x86_64-pc-windows-msvc'
error: rustup is not installed at 'C:\Users\MyUserName\.cargo\bin'`

### Notes

Already tried to uninstall (`rustup toolchain uninstall stable`) then reinstall.

### Rustup version

```console
rustup 1.24.3 (ce5817a94 2021-05-31)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.58.1 (db9d1b20b 2022-01-20)
```

### Installed toolchains

```console
Default host: x86_64-pc-windows-msvc
rustup home:  C:\Users\MyUserName\.rustup

installed toolchains
--------------------

stable-x86_64-pc-windows-msvc (default)
nightly-x86_64-pc-windows-msvc

active toolchain
----------------

stable-x86_64-pc-windows-msvc (default)
rustc 1.58.1 (db9d1b20b 2022-01-20)
```

**Comment by kinnison** [comment]
Okay, so please bear with me as I'm not a Windows user by nature, so I may ask some stupid questions.

1. Are you sure that the full cargo home is present? i.e. `C:\Users\MyUserName\.cargo\bin` and does that have the rustup binary and proxies in it?
2. Is that full path in your `$Env:path` ?
3. Are you sure that the `rustup` you get when you run it in your shell is that rustup?

It could be that you have two versions of rustup installed and they are conflicting - ditto you may have a rustup installed as administrator and one as your user perhaps?

If none of that yields any clues, we can think again.

**Comment by CrommVardek** [comment]
That's no stupid question, here is the result of `ls` in `C:\Users\MyUserName\.cargo\bin` :

> Mode                 LastWriteTime         Length Name
> ----                 -------------         ------ ----
> d-----        09/02/2022     21:30                git
> d-----        09/02/2022     21:31                registry
> -a----        09/02/2022     21:30              0 .package-cache
> -a----        09/02/2022     21:04        9284608 cargo-clippy.exe
> -a----        09/02/2022     21:04        9284608 cargo-fmt.exe
> -a----        09/02/2022     21:04        9284608 cargo-miri.exe
> -a----        09/02/2022     21:04        9284608 cargo.exe
> -a----        09/02/2022     21:04        9284608 clippy-driver.exe
> -a----        09/02/2022     21:04        9284608 rls.exe
> -a----        09/02/2022     21:04        9284608 rust-gdb.exe
> -a----        09/02/2022     21:04        9284608 rust-lldb.exe
> -a----        09/02/2022     21:04        9284608 rustc.exe
> -a----        09/02/2022     21:04        9284608 rustdoc.exe
> -a----        09/02/2022     21:04        9284608 rustfmt.exe
> -a----        09/02/2022     21:04        9284608 rustup.exe


rustup is indeed there. 

2. Yes, the PATH contains `C:\Users\MyUserName\.cargo\bin`, oddly it also contains ` C:\Users\MyUserName\.cargo\bin\bin`
3. I was also wondering that, I did not mentioned it but I ran `.\rustup.exe update` from  `C:\Users\MyUserName\.cargo\bin` same error.

**Comment by ChrisDenton** [comment]
Hm, does it work if you do `rm env:CARGO_HOME`? I.e. remove the `CARGO_HOME` environment variable in the current session.

**Comment by kinnison** [comment]
Also, it's odd that your `bin` directory contains what looks very much like a `CARGO_HOME` too (`git`, `registry`, etc.) which suggests to me that you've had two conflicting installs at times, with bad environment variables.  It may be sensible to remove *any* `CARGO` or `RUSTUP` related environment variables, remove the `.cargo\bin` bits of `PATH` and manually delete your rustup and cargo homes, and then install from scratch.

**Comment by CrommVardek** [comment]
@kinnison : Sorry for the delay. 

I've cleaned everything, removed the cargo and rustup home from path and freshly installed rustup. And now, no more errors. This is still odd error. But I guess it is resolved by simply removing everything and re-installing. Thanks ! 

I might have installed rust once forgot about it and install it again, hence the issues and indeed that would have most likely resulted to conflicting installs as you suggested.

Thanks for your time and for the help !

**Comment by dsherret** [comment]
I had this issue on Windows after changing my CARGO_HOME to a different location. Reinstalling rustup fixed it for me so that the rustup binary ends up in the new cargo home, but kind of strange that this error appears when rustup is already found on the path (not a big deal though).

**Comment by burgil** [comment]
I've found a way to fix it, Had the same issue on Windows 10, Since I got here via a top Google search for `error: rustup is not installed at` I believe I'm at the right place and that my findings will help others.

### How I fixed it:
I had this issue for the past 2 months and 2 major rustc versions, I moved rust and cargo to another drive due to space concerns on my C drive and today while updating to v1.80 I got the `error: rustup is not installed at` again, determined to fix it, here I am with a tutorial how to move rust and cargo to another drive, safely/correctly/without errors.

My issue really came down to note number 2 that I've mentioned bellow, but here is the full scope of how I got it working:

Move the folders `C:\Users\YOUR-USERNAME\.cargo` and `C:\Users\YOUR-USERNAME\.rustup` to the new location and set the following environment variables:

CARGO_HOME `A:\cache\.cargo`
Add to Path: `A:\cache\.cargo\bin` (< This is what I was missing)
RUSTUP_HOME `A:\cache\.rustup`

![image](https://github.com/user-attachments/assets/c727598f-75e5-4910-9213-cf0ee44de6e4)

### Important notes:
1) Make sure to close all command prompt windows, and even your code editor before, otherwise you will get errors like file already in use, can't clean temp files, and the changes in the environment variables requires it otherwise the new variables won't do any changes.
2) Make sure all the content of the folder `C:\Users\YOUR-USERNAME\.cargo\bin` is inside the new path `A:\cache\.cargo\bin`
3) If you're still having issues make sure you run cmd as administrator
4) If you are getting `warning: tool is already installed, remove it from..` - Go to that folder and manually remove them and then run `rustup update stable` again 
5) If you are getting `Unable to clean up A:\cache\.rustup\tmp: Os { code: 5, kind: PermissionDenied, message: "Access is denied." }` simply make sure you've closed your code editor and all other command prompts before you try again.
6) Notice you may need to run both `rustup update stable` and `rustup update` for the cleanup process to work.

Below is a visual look that shows what you're expected to have on those folders, Hope it helps!

![image](https://github.com/user-attachments/assets/70814add-2462-4e06-920a-447515a01e66)
![image](https://github.com/user-attachments/assets/9546041c-d3f9-4f90-84d1-5405812a98f8)
![image](https://github.com/user-attachments/assets/b3b70de4-6158-475a-b154-ede0e04d31be)
![image](https://github.com/user-attachments/assets/957809a6-8c91-4b58-bd8c-f4590552c76d)
![image](https://github.com/user-attachments/assets/aa1062d1-dcff-4039-94ae-745fc4691468)

`.rustup/settings.toml`:
```toml
default_toolchain = "stable-x86_64-pc-windows-msvc"
profile = "default"
version = "12"

[overrides]
```
