### ISSUE TITLE
installation on armv5tel

### ISSUE THREAD

**Issue by raderarn** [rust-lang/rustup#3037]
### Problem

amvv5te is in tier 2, so I try to install.
I have downloaded the rustup_init for arm-unknown-linux-gnueabi. But when I try to install it I get an errorcode:

> rustup-init: 1: Syntax error: word unexpected (expecting ")")

### Steps

wget https://static.rust-lang.org/rustup/dist/arm-unknown-linux-gnueabi/rustup-init
sh rustup-init

### Rustup version

```console
-
```

### Installed toolchains

```console
-
```

**Comment by ilyapopov** [comment]
`rustup-init` is an binary ELF executable. You should run it directly, without `sh`

```
$ file rustup-init
rustup-init: ELF 32-bit LSB pie executable, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux.so.3, for GNU/Linux 3.2.101, with debug_info, not stripped
```

**Comment by raderarn** [comment]
yes, if i run ./rustup-init i get "illegal instruction"

**Comment by kinnison** [comment]
I believe the `arm-unknown-linux-gnueabi` is an armv7 triple, I doubt it'll work hosted on armv5tel.  Your target would be the `armv5te-unknown-linux-gnueabi` triple which is tier 2, not tier 2 with host tools.  As such I wouldn't expect rustup to be of value to you because you won't get rustc/cargo for that platform either.  You will need to use a different system and cross-compile for armv5te.

**Comment by kinnison** [comment]
As such, this isn't a bug in rustup, so I'm going to close the issue
