### ISSUE TITLE
Cargo is not applicable to 29 / 9 toolchain (Linux)

### ISSUE THREAD

**Issue by blyxyas** [rust-lang/rustup#3076]
### Problem

I try to run cargo in today's nightly build of the toolchain, and it gives me this error:

```
error: the 'cargo' binary, normally provided by the 'cargo' component, is not applicable to the 'nightly-2022-09-29-x86_64-unknown-linux-gnu' toolchain
```

### Steps

1. Install today's nightly toolchain
2. Run `cargo`

### Version

```text
cargo 1.63.0 (fd9c4297c 2022-07-01)
release: 1.63.0
commit-hash: fd9c4297ccbee36d39e9a79067edab0b614edb5a
commit-date: 2022-07-01
host: x86_64-unknown-linux-gnu
libgit2: 1.4.2 (sys:0.14.2 vendored)
libcurl: 7.83.1-DEV (sys:0.4.55+curl-7.83.1 vendored ssl:OpenSSL/1.1.1n)
os: Arch Linux [64-bit]
```

**Comment by weihanglo** [comment]
Could you provide more details of the issue? Such like

- How do you install rustup? What is the version of rustup?
- What command did you run to install nightly toolchain?
- Providing a verifiable, reproducible example could be helpful.

[Rustup Components History](https://rust-lang.github.io/rustup-components-history/x86_64-unknown-linux-gnu.html) looks healthy today. I can neither reproduce it. Maybe reinstall the toolchain and see if the issue persists?

Anyway, this issue seems to belong to [rust-lang/rustup](https://github.com/rust-lang/rustup). Specifically, [this line](https://github.com/rust-lang/rustup/blob/a7809fe8d1bffdf7ff6598665ff72cc91231d55e/src/toolchain.rs#L364-L367) reports the error.

**Comment by rbtcollins** [comment]
this usually means that that nightly build failed to build cargo

**Comment by weihanglo** [comment]
@rbtcollins I thought components history shows all availables there, no? I am not familiar with components distributions though.

**Comment by blyxyas** [comment]
It was fixed by using
```
rm -r ~/.rustup/toolchains/nightly-2022-09-29-x86_64-unknown-linux-gnu
cargo
```

(While using nightly as default)
