### ISSUE TITLE
rustup-init 1.25.2 now requires glibc >=2.14

### ISSUE THREAD

**Issue by Aaronus23** [rust-lang/rustup#3203]
### Problem

I cannot run rustup-init to install rust 1.63.0 since its asking for glibc>=2.14, i think this is odd since there are many rust versions that support older versions of glibc.

### Steps

run rustup-init (i have tried this target, not sure about others [x86_64-unknown-linux-gnu](https://static.rust-lang.org/rustup/dist/x86_64-unknown-linux-gnu/rustup-init) ) on RHEL 6 (or some other distro with lower glibc support) and it will fail

### Possible Solution(s)

link rustup-init against some lower glibc version

### Rustup version

```console
none
```

### Installed toolchains

```console
none
```

**Comment by J-ZhengLi** [comment]
Right... Rust did [increase its glibc requirement](https://blog.rust-lang.org/2022/08/01/Increasing-glibc-kernel-requirements.html) after rustup released its 1.25.1 version, so I guess there should be a glibc version check for `self_update` and at least show a warning before automatically updates itself~

**Comment by rbtcollins** [comment]
This is documented in that blog post - effectively everything built in rust-lang CI will have that new minimum requirement, because we're building with current Rust stable.

There are two cases: new installs, and upgrades. Upgrades first:

We have no out of band method for telling rustup that a particular upgrade needs some predefined test before going ahead, and we'd need to build a point release of *all* the older rustups, with an old rust, to signal to those rustup installations that they should check - and then not upgrade.

And finally, even if we did all that, the folk upgrading rust wouldn't be able to use their upgraded stable rust, because the requirements wouldn't be met. In fact, the older rustup will upgrade their stable toolchain and break it even if rustup itself didn't upgrade, because the same lack of fine grained requirements checking applies to the distributions of rust that rustup installs.

Ok, now the new install case.

For that, we have a shell script that runs to select the right binary and download it.

I think a patch to that, to check kernel and glibc requirements is fine. It could even download an older rustup (with a warning of course) to facilitate people that need to test on older machines for some reason.

**Comment by rbtcollins** [comment]
But do note that GLIB is over 10 years old
2012-03-21 GLIBC 2.15 GNU libc 2.15 released

So I'm also completely happy if we do nothing at all and close this, since the only folk running such old installs deliberately, outside of the explicit testing case, are (roughly): RH and Suse and other enterprise distributions with *funding* coming in from customers, banks and other hyper risk averse slow-moving organisations that again have money to spend on not-upgrading, and the occasional random individual with an old install or arch or whatnot that can be upgraded if they choose.

**Comment by Jongy** [comment]
I just encountered it now.

I think, a small fix that could allow me to use the vanilla `curl https://sh.rustup.rs` would be if I could pass the relevant archive URL. The installer from `https://static.rust-lang.org/rustup/archive/1.25.1/x86_64-unknown-linux-gnu/rustup-init` works fine for me on CentOS 6, so if I could pass it via an env var it'd solve me case. The script accepts `RUSTUP_UPDATE_ROOT` but adds `/dist/` on top of it, while I need `archive/...`.

EDIT: well even though the older `rustup-init` installer runs on CentOS 6, the rustc etc it installs do not anymore. Dropping my idea then :cry:

**Comment by cuviper** [comment]
I suggest using the standalone installers:
https://forge.rust-lang.org/infra/other-installation-methods.html#standalone

The `tar.gz` links are for the current stable, but if you change the version number in the link, you can get older versions that way too.

**Comment by fabiodepin** [comment]
Try:

`cd /usr/src/
wget wget https://static.rust-lang.org/dist/rust-1.63.0-x86_64-unknown-linux-gnu.tar.gz

tar -xf rust-1.63.0-x86_64-unknown-linux-gnu.tar.gz
cd rust-1.63.0-x86_64-unknown-linux-gnu

./install.sh`


Work for me on debian 6

**Comment by Aaronus23** [comment]
Just to clarify, I know how to work around this issue but believe it should still be handled so that the `curl https://sh.rustup.rs ` command works properly for some of the older distros. However devs seem fine with this being broken and since there are many workarounds I am also fine if the issue is closed. Still wanted to put it out there for reference

Edit: simply using rustup-init 1.25.1 is my workaround for clarification

**Comment by rami3l** [comment]
I'm closing this since at the time of writing we're only going to support glibc 2.17+, as per https://doc.rust-lang.org/nightly/rustc/platform-support.html.
