### ISSUE TITLE
Allow rustup run command to work with default

### ISSUE THREAD

**Issue by asafigan** [rust-lang/rustup#3304]
### Problem you are trying to solve

I have to configure my code editor to run rust-analyzer. I have it setup to run rust analyzer through rustup by running `rustup run stable rust-analyzer`. This works great! The problem is if I switch my default tool chain to nightly I have to change my editor's configuration to use the nightly toolchain instead.

### Solution you'd like

I would like to be able to just do `rustup run default rust-analyzer` so when I switch my default toolchain I don't have to change my editor's settings.

**Comment by senekor** [comment]
This issue will be resolved in the next release, 1.26. (see [here](https://internals.rust-lang.org/t/help-verify-rustup-1-26-0-release/18577))

Once rustup installs the proxy for rust-analyzer, it won't be necessary to configure text editors at all anymore. (Edit: I guess that may not be true for all editors. But they can be configured to rust `rust-analyzer`, with the same result.) Text editors will just be able to discover rust-analyzer on the PATH and the correct toolchain will be picked by the proxy automatically.

I really wish [this issue](https://github.com/rust-lang/rustup/issues/2411) was reopened and tagged with `fixed-next-release`. The fact that it has been closed is very confusing, because the feature hasn't shipped yet and the [documentation of rust-analyzer](https://rust-analyzer.github.io/manual.html#rustup) links to that issue.

**Comment by keysmashes** [comment]
Sorry – will `rustup run default` start working next release, or is it just that the `rust-analyzer` proxy will start being installed? I'm not the original author, but I think I do actually need the former, ideally. for reasons unrelated to r-a. (`rustup run "" ...` appears to work, but feels moderately fragile...)

**Comment by senekor** [comment]
I'm not aware that `rustup run default` will change in behavior. I only know that the proxy for `rust-analyzer` will start being installed.

What is the problem you are trying to solve? As far as I'm aware, the purpose of `rustup run X Y` is to run Y... but overriding the default toolchain with X. So I'm not sure what the purpose is of "overriding" the default toolchain with the default one. Can't you just run Y ?

**Comment by keysmashes** [comment]
hah, ok, apparently I didn't look closely enough and I don't actually need this (because the nixpkgs rustup derivation [has its own list](https://github.com/NixOS/nixpkgs/blob/ca3bd88b64bae837e52f3c2dfb2d382cb54e4856/pkgs/development/tools/rust/rustup/default.nix#L68-L71) of rustup proxies that it supports), so I can do `${pkgs.rustup}/bin/cargo` just fine. my thinking was "I know where the `rustup` binary is (`${pkgs.rustup}/bin/rustup`), but not necessarily `cargo` or anything else".

**Comment by l4l** [comment]
So apparently this was not fixed in "next release". I'm still interested in `rustup run default` behavior. Mind me to open a PR? Shouldn't be that hard to implement

**Comment by rami3l** [comment]
> So apparently this was not fixed in "next release". I'm still interested in `rustup run default` behavior. Mind me to open a PR? Shouldn't be that hard to implement

@l4l Please feel free to do so, but I'm also curious about your particular use case.

The original issue looks like an XY problem to me: if a proxy exists, then no `rustup run` call should be required, since you can simply do `<proxy>` instead.

**Comment by senekor** [comment]
@l4l these days I have to run `rustup component add rust-analyzer` once when setting up a new dev machine to install the proxy. After that, running `rust-analyzer` has the expected behavior of using the default toolchain. Does that solve your use case?

**Comment by djc** [comment]
@l4l IMO you should not open a PR until after we've discussed your use case.

**Comment by l4l** [comment]
I think I figured out what was my issue.

My use-case is exactly the same as noted in the topic. I use helix, and for RA I use:

```rust
command = "rustup"
args = ["run", "stable", "rust-analyzer"]
```

So if I need RA for a specific toolchain (e.g for rustc_private) I need to override the "stable" part for particular version, otherwise it doesn't work. It happens I have a separately installed rust-analyzer package which is obviously resolved first instead of rustup proxy. So basically removing the package is the right solution for me. Other option indeed to point to the rustup proxy full path.

Thanks for the hints, was really confused with that.

**Comment by rami3l** [comment]
@l4l Thanks for your clarification! I think I can close this now.

**Comment by javalsai** [comment]
@djc Could we reopen this? Solely for the reasons in the original message, for times where someone just needs to run `rust-analyzer` (or any other component) of the default configured toolchain, there's no way without scripting the toolchain name extracion or hardcoding one toolchain.

Sure this was originally dismissed because the proxy binaries were supposed to do this but I don't think binaries like `rust-analyzer` are proxied at all.

I only need it to properly configure my editor properly rn but I can see how this could prove useful in a lot of other contexts where a program uses a toolchain component that's not proxied. It shouldn't be hard to implement either, I'd be happy to try to implement this if it's welcome.

**Comment by rami3l** [comment]
> Sure this was originally dismissed because the proxy binaries were supposed to do this but I don't think binaries like `rust-analyzer` are proxied at all.
> 
> I only need it to properly configure my editor properly rn but I can see how this could prove useful in a lot of other contexts where a program uses a toolchain component that's not proxied. It shouldn't be hard to implement either, I'd be happy to try to implement this if it's welcome.

Thanks for the feedback, but RA is proxied since a long time ago... In addition we have https://github.com/rust-lang/rustup/pull/4324 so you can set a wrapper script in your PATH to call the default RA outside of your project if you want.

I can see a need for more "keywords" for certain toolchains, this is on our roadmap as well but we have to clean up allowed toolchain names first :)

For your particular case it'd be hardly useful for rustup to resolve the default toolchain for you since it has been overridden when you enter the project, so you need to be able to express something more than that. Something along the lines of https://github.com/rust-lang/rustup/issues/4636.
