### ISSUE TITLE
Provide a proper package for macOS with notarized binaries.

### ISSUE THREAD

**Issue by arifmetic** [rust-lang/rustup#3422]
### Problem you are trying to solve

As per the current defaults, rustup installs with a script downloading un-notarized binaries in user's home directory and adding it to PATH. This is a pretty bad arrangement security wise.

The other way I found was to download an installer in `.pkg` format, but it wouldn't run on macOS due to failing Gatekeeper check.

### Solution you'd like

Could we get a proper `.pkg` for rustup and the supplementary rust binaries such as cargo and rustc? By proper I mean notarized package that would install notarized binaries in in a directory under `/Applications` directory on macOS. 

This approach is already being used by other toolchains such as **Go**, **CMake** and **ARM GNU Toolchain**.

**Comment by rbtcollins** [comment]
I think there are two distinct things being discussed here.

`rustup` includes the binaries `rustc`, `cargo` etc in the form of hardlinks to `rustup` itself - these are the proxies invoked when you run such a command.

But then rustup also downloads packages of the real rustc and cargo and so on for a given version.

In this bug here we can sensibly discuss a notarised rustup binary, and presumably that would cover the hardlinked proxies as well. However to get notarised distributions of rustc etc that will need to be discussed in the https://github.com/rust-lang/rust bug tracker.

Now, regarding notarised binaries of rustup: I have no idea what is involved, or how it works, nor do I have a Mac. So I'm marking this help wanted : if someone wants to design how it will work, including the interactions with github actions continual deployment, key management and so on, that would be great and I'll be happy to review and offer suggestions.

**Comment by rbtcollins** [comment]
https://github.com/rust-lang/rust/issues/27694 seems to be the canonical signed-binaries thing there.

**Comment by rbtcollins** [comment]
And #1568 is the canonical one for rustup; at least at a bug tracking level I don't see much benefit in having one-per-ecosystem.
