### ISSUE TITLE
Rustup installer prompt or cli argument to install rust on drive in which the user wants instead of C: in windows

### ISSUE THREAD

**Issue by w1redch4d** [rust-lang/rustup#3495]
### Problem you are trying to solve

for now there seems to be no way to tell rustup-init to install rust and cargo on any other drive than the default C: drive on WIndows , An option to change the rust installation drive with rustup would be a good enhancement imo

### Solution you'd like

A prompt in rustup-init after going for customize installation to enter the preferred path in which rust should be installed or a cli argument for the same purpose should do

### Notes
I am willing to contribute on this issue

**Comment by rami3l** [comment]
@w1redch4d Hi! Currently the installation path selection is implemented via environment variables.

Have you tried [setting `CARGO_HOME` and/or `RUSTUP_HOME`](https://rust-lang.github.io/rustup/installation/index.html#choosing-where-to-install) to somewhere else?

**Comment by w1redch4d** [comment]
Yep, ik that as mentioned in #618 , but ig an installation path prompt in rustup-init might be more helpful for people who are just getting started ?

**Comment by rami3l** [comment]
@w1redch4d Thanks for your willingness to contribute on this issue! However, there is indeed a reason why options/prompts haven't been provided for this one:

> Hm, changing the installation dir in the installer comes with some complexity because _after_ installation the environment should be configured with custom values for `CARGO_HOME` and `RUSTUP_HOME` or else it won't work right. Think we should hold off on that.

_Originally posted by @brson in https://github.com/rust-lang/rustup/issues/618#issuecomment-236232923_

---

I see what you mean, but IIUC it is still the case that `CARGO_HOME` is used not only by `rustup`, but also by `cargo` and others. Thus, passing an option to `rustup` indicating what `CARGO_HOME` should be is not very effective: this must be done before even launching `rustup-init` and it must somehow persist, otherwise certain things might go wrong.

Maybe the best thing that we can do currently (without breaking our compatibility promises) could be something like the following:

> > The Rust toolchain will be installed in {RUSTUP_HOME} and cargo will use {CARGO_HOME}.
> > Are these directories ok? 
> >
> > [Input:] Y/n 
> >
> > (on `n`): To install the Rust toolchain in a different directory, set the RUSTUP_HOME and/or CARGO_HOME environment variables to appropriate values before running the installer. (program exit).

_Originally posted by @gnzlbg in https://github.com/rust-lang/rustup/issues/618#issuecomment-504366382_

---

As a point of improvement, in a subsequent PR, you can make `rustup-init` offer to make this change for you (which you can refuse, or course) via something like `[Environment]::SetEnvironmentVariable('Foo', 'Bar', 'Machine')` [on Windows](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_environment_variables?view=powershell-7.2#saving-environment-variables-with-setenvironmentvariable) or by appending to the current `.profile` on Unix, after which it might say ```restart `rustup-init` to proceed with the installation``` and exits.

I'm not sure if this will break anything though... cc @rbtcollins

**Comment by djc** [comment]
I don't think we should offer functionality within rustup to manipulate the environment like that, that feels like opening a can of worms in complexity at a time when we're already quite limited in development capacity. But adding better inline guidance and documentation sounds great to me!

**Comment by rbtcollins** [comment]
I concur.

There is a UI principle: make the common case easy, make the rare case possible.

This case is already possible.

It is not (based on how often it is asked for, and the context when it is asked for) a common case.

So - if it isn't documented, lets document it better. But I don't think we should make the common case harder by adding more prompts.

**Comment by rbtcollins** [comment]
And the docs were added 4 years back. https://github.com/rust-lang/rustup/issues/618#issuecomment-504320017

**Comment by djc** [comment]
Current docs:

```
djc-2021 update-deps pulumi $ ./rustup-init

Welcome to Rust!

This will download and install the official compiler for the Rust
programming language, and its package manager, Cargo.

Rustup metadata and toolchains will be installed into the Rustup
home directory, located at:

  /Users/djc/.rustup

This can be modified with the RUSTUP_HOME environment variable.

The Cargo home directory is located at:

  /Users/djc/.cargo

This can be modified with the CARGO_HOME environment variable.
```

So yes, this seems pretty friendly to me already.
