### ISSUE TITLE
Clipboard copy icon misaligned on Safari

### ISSUE THREAD

**Issue by mistydemeo** [rust-lang/rustup#3512]
### Problem

On Safari (macOS and iOS), the clipboard copy icon is misaligned. It clips halfway through the top of the button instead of being in the centre. I'm using macOS 14.0 and iOS 17.0.3.

![image](https://github.com/rust-lang/rustup/assets/780485/7b83bad2-7e63-4560-9d20-75c0fc66c3a0)

### Steps

1. View rustup.rs using Safari

### Rustup version

```console
N/A
```

### Installed toolchains

```console
N/A
```

**Comment by djc** [comment]
This looks like a WebKit bug, maybe https://bugs.webkit.org/show_bug.cgi?id=202588? The code lives at https://github.com/rust-lang/rustup/blob/master/www/index.html#L55 if anyone wants to take a whack at coming up with a more compatible solution.

**Comment by rami3l** [comment]
@mistydemeo May I know what page you were on? I saw this on my iPad today with https://www.rust-lang.org/tools/install:

<img width="1168" alt="image" src="https://github.com/rust-lang/rustup/assets/33851577/c4c8dfd1-e32e-4d3a-806c-1014a0256c0e">

... maybe the style has changed since?

---

Update: Never mind, I found out: https://rustup.rs.

**Comment by noirgif** [comment]
The fix in #3696 does not seem to reflect in the web page yet. So I think this should be left open for now.

**Comment by rami3l** [comment]
@noirgif Indeed, but there is nothing more we can do about it except waiting for the new release to happen in #3501 (we do not get to control what's on rustup.rs right now, which is the responsibility of the release team).

And OTOH we should not track this issue with #3501 since if we did that it would be tracking too many issues.

**Comment by noirgif** [comment]
If the deployment does not happens with the merge, but with a new release, then it makes sense to close this issue. Thanks for the explanation.
