### ISSUE TITLE
warning: spurious network error (3 tries remaining): [7] Couldn't connect to server (Failed to connect to 127.0.0.1 port 4780 after 0 ms: Couldn't connect to server)

### ISSUE THREAD

**Issue by Rock0007** [rust-lang/rustup#3645]
### Problem

![image](https://github.com/rust-lang/rustup/assets/78554483/3215c6a6-fadb-454b-81c8-2dc472236007)
![image](https://github.com/rust-lang/rustup/assets/78554483/8c877608-5de9-4f38-9281-798dfa5d9b2b)

When I run `cargo run` i'm getting the following error:

![image](https://github.com/rust-lang/rustup/assets/78554483/613fcc4e-b0d9-4459-80d7-504d4d89fdcd)

### Steps

1. I have Set 
`set HTTP_PROXY=http://proxy.example.com:8080
set HTTPS_PROXY=http://proxy.example.com:8080
`
2. `cargo run --verbose --locked --offline
` still same issue.
3. `[source.crates-io]
registry = "https://github.com/rust-lang/crates.io-index"
` though no changes.

Nothing worked for me.

### Possible Solution(s)

Please help me with possible solutions. I have been stuck from a week on this issue.

### Rustup version

```console
rustup 1.26.0 (5af9b9484 2023-04-05)
```

### Installed toolchains

```console
Default host: x86_64-pc-windows-msvc
rustup home:  C:\Users\Rock\.rustup

stable-x86_64-pc-windows-msvc (default)
rustc 1.75.0 (82e1608df 2023-12-21)
```

**Comment by rami3l** [comment]
@Rock0007 Thanks for filing this issue!

However, this looks like a proxy configuration problem rather than an actual Rustup issue. Your proxy points to `127.0.0.1:4780` currently.

Rustup should accept `HTTPS_PROXY` and friends if you have correctly set them up. However, the `set *` command you used looks like a Unix command but you're running it on Windows?

My personal suggestion is that you should check your system to find out why and where that `127.0.0.1:4780` got set up, and change it to the correct value accordingly.

Have a nice day! :)

**Comment by Rock0007** [comment]
Hey @rami3l 

I have set proxy to `$env:HTTP_PROXY = "http://127.0.0.1:4780"
` on windows Powershell.

and also in my terminal.

still facing the same issue. Pls guide me out.

**Comment by rami3l** [comment]
@Rock0007 If `http://127.0.0.1:4780` is indeed your proxy, then clearly it's recognized by `rustup` but the proxy itself is not working alright. In that case, you should probably contact your IT manager or proxy service provider.

Sorry for the inconvenience!

**Comment by Rock0007** [comment]
@rami3l okay then I'll try to set proxy `http://127.0.0.1:4780` for rustup.

can you give me the command?

I tried `rustup.exe set proxy http://127.0.0.1:4780` says that its not correct command.

**Comment by rami3l** [comment]
@Rock0007 Looking at your screenshot, Rustup is already using `http://127.0.0.1:4780` as your proxy server, so there is nothing to be set up. Rather, your proxy has a bad connection, that's why your `cargo run` didn't work.

**Comment by Rock0007** [comment]
@rami3l So what is the way to solve this issue?
Alternative Version or anything up ?

**Comment by rami3l** [comment]
@Rock0007 According to your descriptions I can see that you have correctly pointed Rustup to a proxy server, and Rustup is working as intended, but unfortunately that proxy server is not working, and there is nothing I can do for you apart from pointing that out. Sorry :(

You should get a working proxy server by fixing it yourself rather than asking us since we know nothing about it, and more importantly, providing you support on fixing a proxy server is obviously out of the scope of this project.

**Comment by rami3l** [comment]
@Rock0007 I suggest you try one of the user forums such as <https://users.rust-lang.org/> to see if someone can help.

**Comment by Rock0007** [comment]
Yeah okay
