### ISSUE TITLE
Investigate certificate pinning

### ISSUE THREAD

**Issue by brson** [rust-lang/rustup#389]
Right now rustup downloads everything over HTTPS from two sources, rustup.rs, and static.rust-lang.org. To avoid DNS hijacking attacks we probably need to enforce further constraints on the certs the servers produce.

I'm not sure offhand how important this is if we were to both sign the rustup-init binaries and validate all the rust and rustup binaries' signatures. And I'm not sure if it's a substitute for validating the signatures, but I suspect not.

**Comment by Yamakaky** [comment]
I think signing the binaries is sufficient. I don't see how validating the certificate would be more secure.

**Comment by ssokolow** [comment]
@Yamakaky It might make any flaws discovered in the signing verification more difficult to exploit, depending on the attack vector. Aside from that, nothing readily pops to mind.

**Comment by benaryorg** [comment]
An overview of OpenBSD's distribution model:

- downloads over HTTP, HTTPS and FTP
- mirrors provided by third parties
- actual files downloaded are signed by a key that is distributed with the "installer"
- different signing key for each version (not very applicable due to short interval for rust, though)

This allows people to more easily use mirrors/caching.
If the first installation is done over HTTPS it can already bring two public keys (current one and "fallback" one that can also be used for regular rotation).
We'd be back at [TOFU](https://en.wikipedia.org/wiki/Trust_on_first_use) which is just as security works nowadays.

**Comment by kpcyrd** [comment]
I think at least the stable releases should be a perfect target for [binary transparency][1]. Not sure how viable this is for nightly.

[1]: https://wiki.mozilla.org/Security/Binary_Transparency

**Comment by RyanSquared** [comment]
Please note that HPKP - HTTP Public Key Pinning - has been removed in Chrome and other browsers due to some pretty significant issues.

## Issue 1

The system relies on TOFU, and if someone implements a MITM for the first connection, then later connections that might not be MITM'd will not be able to connect because the pinned certificate is not the one currently offered.

## Issue 2

Certificates expire. Certificates get replaced. Certificates can differ between servers. If any of these things happen, you no longer have a way to reliably get the new certificate because how can you verify it if you can't continue to trust the source it came from?

---

Debian uses HTTP by default for downloading packages, as do other distributions. It is a reliable way to install software assuming that the keys used for signing packages are up to date.

Please correct me on anything I missed or misunderstood with these issues.

**Comment by mleonhard** [comment]
Without certificate pinning, could an attacker MITM a connection and cause the client to install an old vulnerable binary?

**Comment by kpcyrd** [comment]
@mleonhard without certificate pinning:
- a CA could issue a certificate for rustup.rs and static.rust-lang.org and use this for targeted attacks
- corporate setups usually have custom root certificates installed to intercept tls connections and could serve you modified binaries

Everbody else is fine until the servers hosting the files get compromised.

To be able to mitigate a compromise of the servers hosting the files and because we need to support corporate setups with intercepting proxies it might be a better idea to use signed releases instead of relying exclusively on TLS.

Something we might want to look into is https://theupdateframework.io/

**Comment by kinnison** [comment]
Certificates are (at least currently) managed via Amazon's cloudfront stuff AIUI.  Given that we're not going to be pinning a particular pubcert because we're not in direct control of when the certificate changes happen, and we cannot guarantee people update rustup in time.

TUF is an interesting thing, and we are looking at it, though we're probably going to deviate from it completely since it's not just `rustup` but also toolchains which we have to care about, and TUF feels very odd at that point.

I'm going to close this because cert pinning isn't on the cards for now.  There's other issues for thinking about signed channels etc.
