### ISSUE TITLE
'no updatable toolchains installed'

### ISSUE THREAD

**Issue by liigo** [rust-lang/rustup#395]
After my first runing `rustup-init.exe`, I got `rustup.exe`, `cargo.exe` and `rustc.exe` installed at `.cargo/bin`, that's OK. But no toolchain was installed normally for network reasons.

Then I run: `rustup update`
... and expect it will install some toolchains for me, but it just says:

`info: no updatable toolchains installed`

Yes I can do:

```
rustup update stable
rustup update beta
rustup update nightly
rustup update any_other_if_exists
```

But I think at least a `rustup update ALL` (does the similar work as rustup-init) will make my life easier.

---

Just another thing:

```
C:\Users\liigo>cargo
error: no default toolchain configured
```

Why not suggest user HOW to config or install a toolchain here?

**Comment by Diggsey** [comment]
`rustup update` no longer updates nightly/beta/stable, it updates all the installed toolchains: in this case you have none. Once you've installed those toolchains for the first time, there's no need to update them separately, a single `rustup update` will update all of them.

I think the issue here is the lack of a dedicated `toolchain add/install` command. (Also, yes we should say how to configure a default toolchain)

**Comment by brson** [comment]
> Why not suggest user HOW to config or install a toolchain here?

That's a good idea.

**Comment by pickfire** [comment]
Is this still valid?
