### ISSUE TITLE
How to distinguish rustup-`cargo` from system-`cargo`?

### ISSUE THREAD

**Issue by Nadrieril** [rust-lang/rustup#3990]
### Problem you are trying to solve

I write [a rustc driver](https://github.com/AeneasVerif/charon), which requires a very specific nightly. Rustup handles that magnificently, except if the user also has rust installed through their system package manager. Today, I don't know a way to tell which cargo will be run when I run `cargo`, and using the non-rustup cargo creates unscrutable errors.

### Solution you'd like

I'd like to be able to tell if the `cargo` in `PATH` comes from rustup or somewhere else, so I can warn the user. Having "rustup" in the output of `cargo --version` would be sufficient for example.

**Comment by rami3l** [comment]
@Nadrieril Thanks for filing this issue.

This should be possible without changing anything from our side, since our `cargo` is just a symlink that points to your `rustup` binary, and I don't believe that's true for whatever `cargo` you've installed from other sources.

You can also call `rustup which cargo` to see what binary will be called by `rustup` ahead-of-time, if you're sure the user will be using `rustup`, that is.

**Comment by Nadrieril** [comment]
Is it always the case that the rustup-installed cargo is a symlink to a binary called `rustup`? If so that would indeed solve my problem nicely

**Comment by rami3l** [comment]
> Is it always the case that the rustup-installed cargo is a symlink to a binary called `rustup`? If so that would indeed solve my problem nicely

@Nadrieril Yes, with a minor caveat:

- If you have installed `rustup` from the official script, it should point to `rustup-init`.
- If you have installed it from one of certain package managers (like `apt`), it could also point to `rustup`:

    ```console
    # Ubuntu 24.04 LTS
    > apt install rustup && rustup default stable
    [..]
    > readlink $(which cargo)
    rustup
    > which rustup
    /usr/bin/rustup
    ```

You should be able to check this property with your own installation quite easily.

Of course, this assumes the user didn't expose in their `PATH` the "real" `cargo` binaries downloaded by Rustup, but doing so is against the point of having Rustup as a facade (so that `cargo` can point to different versions) anyway, so I guess you can safely ignore this case.

**Comment by Nadrieril** [comment]
Sounds good, thanks for the help!
