### ISSUE TITLE
Rustup Init Exe Question

### ISSUE THREAD

**Issue by coffeebe4code** [rust-lang/rustup#4110]
Very sorry for making an issue, i didn't see a discussion board anywhere.

I am making a programming language, and need the Windows Linker just like rustup does.

Where is the code for the rustup init exe which actually runs the visual studio build tools installer? I noticed it prompted me when trying to install rust on windows. and was like thats what i need!

Additionally, where is the code/setup for how rustup knows where to look for the developer command console, and how it executes linker commands from within that shell?

Thank you!
Sorry for opening an issue. if you need to send me somewhere else. please do.

**Comment by ChrisDenton** [comment]
rustup-init isn't really doing anything too special. It's just downloading and running the Visual Studio installer like you would if doing it manually from https://visualstudio.microsoft.com/vs/

The only special thing is that it uses command line arguments to tell it what to install instead of having the user select it manually. See https://github.com/rust-lang/rustup/blob/master/src%2Fcli%2Fself_update%2Fwindows.rs#L290

For setting up the linker and libraries used by rust, see the cc crate https://github.com/rust-lang/cc-rs/blob/main/src/windows/find_tools.rs. Rustup itself only uses this to test if everything is installed correctly.

**Comment by coffeebe4code** [comment]
> For setting up the linker and libraries used by rust, see the cc crate https://github.com/rust-lang/cc-rs/blob/main/src/windows/find_tools.rs. Rustup itself only uses this to test if everything is installed correctly.

okay, so is it cargo which executes a sub shell with the developer console? How does it know the path.?

**Comment by ChrisDenton** [comment]
No subshell is used. Instead rustc (the compiler) uses the code I linked. That code uses an API to ask Visual Studio where it is installed and where binaries and libraries are located.

**Comment by ChrisDenton** [comment]
Here's the file that contains the low-level COM API definitions that are used https://github.com/rust-lang/cc-rs/blob/main/src%2Fwindows%2Fsetup_config.rs

**Comment by coffeebe4code** [comment]
Thank you for the information. I can use this to get what I need.
