### ISSUE TITLE
rustup-init.sh: unknown macOS major version

### ISSUE THREAD

**Issue by harry-xm** [rust-lang/rustup#4119]
In `check_help_for()`, there is a branch for macOS that treats all versions newer than Big Sur as "unknown macOS major version."

Normally this branch is not executed, but before commit a9c4362a1b256ce56ef6a567b0ce46a474b8cd28 there was a brief period where it could be reached when `curl` is too new.

Is the check still necessary?

https://github.com/rust-lang/rustup/blob/dc9d072c34eccbee2d9249daea177b9c4263c5da/rustup-init.sh#L732-L739

By the way, `:` is missing on the last line of `warn`, which is inconsistent and might worth fixing.

**Comment by rami3l** [comment]
@harry-xm Thanks for reporting this! Indeed this part of the script has been out of date since quite a while ago.

I think it shouldn't be too hard to change `11.*` to something like "anything >= 11", maybe by issuing `sw_vers -productVersion | cut -d. -f1` in the `*)` branch?

PS: I can find some time to fix this, and in the meantime please feel free to send a PR over if you like :)
