### ISSUE TITLE
List triples available for download

### ISSUE THREAD

**Issue by kornelski** [rust-lang/rustup#482]
I know rustup can install Rust for several platforms, but I don't remember the exact spelling of nicknames for platforms, cpus and runtimes and dashes/underscores between them.

`rustup toolchain list` only lists triples that I have already installed. I'd like to be able to list all triples for all platforms that rustup is able to install, so that I can see what platforms are supported and choose the best variant among available ones.

**Comment by brson** [comment]
Agreed there should be some way to do this.

**Comment by donhcd** [comment]
this might be slightly off-topic, but if I want to get a nightly from a certain time period, it doesn't seem like there is any way other than to simply guess dates until I find one that works

**Comment by kinnison** [comment]
These days you could `rustup target list` and then "hope" you can fetch a toolchain for the particular one, otherwise there's plenty of documentation on the forge and other places about platform support.  As such I'm going to close this issue.  If it remains a thorn in your side then a fresh issue which proposes a UX and mechanism for us to acquire the valid host list would be appreciated.

**Comment by kornelski** [comment]
~possible target platforms can be listed with:

```bash
rustc --print target-list
```

**Comment by kinnison** [comment]
Targets are not the same as available *hosts* which is what you asked for. If all you want is to get the list of available targets for downloading into a toolchain you already have, then `rustup target list` will do that.
