### ISSUE TITLE
Make https://static.rust-lang.org/rustup/dist return an index

### ISSUE THREAD

**Issue by raphaelcohn** [rust-lang/rustup#722]
It'd be mighty handy if `https://static.rust-lang.org/rustup/dist` returned an index rather than an error - that way one could quickly explore what's available.

**Comment by kinnison** [comment]
What would you hope to get from this index?

**Comment by gibfahn** [comment]
I'd like to see a list of files, like how in Node.js there's [a link on the download page](https://nodejs.org/en/download/) called `All download options` which points to https://nodejs.org/dist/v10.16.3/ . This makes it really easy to see what the latest downloads are and find things.

In the [top-level of the Node.js `dist`](https://nodejs.org/dist/) page there is also an [`index.json`](https://nodejs.org/dist/index.json) and an [`index.tab`](https://nodejs.org/dist/index.tab), the former easiest for Node.js tooling, the latter easiest for shell scripts. I seem to recall from when I starred this issue and was looking at this that there's a `toml` file with the relevant info in `rustup/dist`, but I don't remember exactly, and can't easily browse to check.

I was trying to work out what files were available at what URLs, and ended up having to look at the rustup source to find out. Docs would be nice, but browsable directories would be even nicer.

**Comment by kinnison** [comment]
That sounds quite interesting.  Our dist trees are s3 buckets which don't produce indices by default I believe.  However it'd be part of the rust build process which would have to generate those indices since `rustup` only consumes that content and isn't in charge of it.

I suggest that you look to the `rust-lang/rust` repo to see if anyone else is discussing such a feature.  You could also pop onto the rust-lang Discord server and visit, hmm `#infra` I guess, or perhaps `#release` since those teams are responsible for the dist server and the content on it respectively.

**Comment by raphaelcohn** [comment]
@kinnison Disappointing. I've ended up building my own automation infrastructure in this space.

**Comment by gibfahn** [comment]
Raised in `rust-lang/rust`: https://github.com/rust-lang/rust/issues/66474
