### ISSUE TITLE
Shrink size of default installation

### ISSUE THREAD

**Issue by bluss** [rust-lang/rustup#837]
This is the companion issue to https://github.com/rust-lang/rust/issues/37971

The default installation (for some toolchains at least) contain duplicate files. I know these come from different components, so there is no one easy place to fix this, nor is the overall structure of rustup bad. (It's reaching some awesome goals with multi toolchain and multi target installs).

The fact remains: The default install uses completely identical duplicate files. This means that there is an opportunity to save download size, install size or both.

**Comment by Diggsey** [comment]
One way to improve this would be to stop including compiler dependencies in the set of shared libraries for the target. For projects that need them, the compiler libraries could become a separate component, or a normal cargo dependency.

**Comment by Diggsey** [comment]
The problem with the above is that these dependencies are currently used by compiler plugins, which leaves four possibilities that I can see:
1) Hard-link duplicates - this is difficult to do with the current component system, and won't help with the redundant compiler libraries for other targets which will never be used (since plugins are always compiled for the host)
2) Remove compiler dependencies from components which are not the host target. This is not particularly nice as the current system keeps all of the `libstd` components the same regardless of the host platform, which is nice to have.
3) Separate the compiler dependencies into their own component, which is only a required component for the host platform. This is nice because it fits in well with the existing component system, but it requires changing how rustc is packaged, and it doesn't actually reduce the size of a base rustup installation, only cross compile targets.
4) Add any missing libraries to the set of host libraries, directly in `/lib` as part of the rustc component, and remove them from the `std` component. This requires even more changes to how rustc is packaged, the compiler needs to tell plugins where to find their dependencies, and it makes it impossible to install the component for other targets (which may not be all that useful anyway...). The advantage is that it is the most space efficient, reducing as much redundancy as possible of all the options.

**Comment by lilith** [comment]
In my Dockerfiles, I use this method:

```
#Install nightly Rust and make default
RUN RUSTVER="nightly-2016-11-03" && curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain $RUSTVER -v \
    && rustup default $RUSTVER \
    && HI=$(rustup which rustc) && HI=${HI%/bin/rustc} && export TOOLCHAIN_DIR=$HI && echo TOOLCHAIN_DIR=$TOOLCHAIN_DIR \
    && sudo rm -rf $TOOLCHAIN_DIR/share/doc \
    && sudo rm -rf $TOOLCHAIN_DIR/share/man \
    && sudo rm -rf /home/conan/.multirust/toolchains/${RUSTVER}-x86_64-unknown-linux-gnu/share/doc \
    && ln -sf -t $TOOLCHAIN_DIR/lib/ $TOOLCHAIN_DIR/lib/rustlib/x86_64-unknown-linux-gnu/lib/*.so \
    && rustup show \
    && rustc -V
```
For 2016-11-03, the docker layer above compresses to 212MB (I believe it was 550+MB before stripping docs and duplicates, but that was with an older nightly)

The relevant bit to this topic is `ln -sf -t $TOOLCHAIN_DIR/lib/ $TOOLCHAIN_DIR/lib/rustlib/x86_64-unknown-linux-gnu/lib/*.so`. 

Overall, I think docs and man pages might involve more bytes than the duplicate binaries.

I would like to see Rustup support `--no-docs`, `--no-manpages`, and `--symlink-duplicates` - these alone would be a massive improvement. My script is a bit fragile when installation structure changes - rustup would be in a better position to handle links vs. duplicates.

I don't know enough about Rust to know if it's feasible to reduce the installation size below 212MB without breaking compiler plugins or rendering it unusable for a CI environment. Thoughts?

**Comment by brson** [comment]
We could cut the installation in half trivially by teaching installation to hardlink the host files to the target files. There are some complexities in modifying rust-installer.

**Comment by Diggsey** [comment]
@brson But we use the same packages for libstd, regardless of whether it matches the host triple or not.

**Comment by jgonera** [comment]
It would be really great to at least add `--no-docs`. This is now over 200MB of useless files in a Docker image that I use in CI:

```
# du -sh /root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/share/*
267M	/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/share/doc
128K	/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/share/man
36K	/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/share/zsh
```

**Comment by kinnison** [comment]
The primary "big"ness was docs which 1.20 allows you to bypass by means of the `minimal` profile.

**Comment by bluss** [comment]
This bug was reported by citing the duplicate files that exist inside the same specific toolchain install. What I can see, some of these still remain. I don't think this has been solved, for that reason.

**Comment by kinnison** [comment]
I agree that there remain some duplicated files, though I also feel that is the domain of the release team rather than `rustup` itself.  It's possible that if we can work some kind of `ostree` like magic in the future then even duplicated content from the releases woud be mitigated, but right now I don't think it's our responsibility in `rustup`.
