### ISSUE TITLE
Install prefix

### ISSUE THREAD

**Issue by cholcombe973** [rust-lang/rustup#945]
This new version of rustup no longer supports an install prefix.  I need that for my automated builds in [snappy](https://github.com/snapcore/snapcraft/blob/master/snapcraft/plugins/rust.py).

**Comment by brson** [comment]
rustup installs to two locations, represented by `CARGO_HOME` and `RUSTUP_HOME`, and that cannot be represented with a single prefix. To change where rustup installs, set both these variables while running rustup-init. Note though that these two environment variables must remain set during execution of the Rust toolchain.

I believe this is yet-undocumented, and there may be better interfaces.

cc https://github.com/rust-lang-nursery/rustup.rs/issues/994

**Comment by cholcombe973** [comment]
@brson thanks! I'll give this a shot soon. I think that'll solve my issue

**Comment by kornelski** [comment]
BTW, snapcraft in Debian remains broken by this change. Since that's a built-in plugin, I don't have a way to fix it.

Given that Debian moves at glacial pace, this is going to remain defunct for a long time. It'll be best if Rustup re-added `--prefix`, `--disable-sudo` and `--save`, at least as no-ops.
