### ISSUE TITLE
Poor user experience installing Rust on Windows 7

### ISSUE THREAD

**Issue by mark-summerfield** [rust-lang/rustup#961]
See https://github.com/rust-lang/rust/issues/40054

**Comment by kbknapp** [comment]
I'm not a Windows guy, but needed to use it for a particular project and literally ran into this. exact. issue. Even if `rustup` couldn't do all the downloading and installing automagically, I think presenting those links in stand out, readable fashion would be a good an interim solution.

Edit: corrected the wording

**Comment by brson** [comment]
This is because the MSVC build of rustup presently dynamically links to CRT. The next release will fix that.

Still, I am surprised both of you ran into this. The main installation flow directs all Windows users to the -gnu builds (which work the exact same as the -msvc) builds, and those should not suffer this problem.

**Comment by Diggsey** [comment]
Could you clarify whether you were using the -msvc build of rustup or the -gnu build? Both builds of rustup are capable of installing both -msvc and -gnu versions of the rust toolchain, which is why `rustup.rs` always links to the -gnu version of rustup.

Currently the only requirement should be on the VC++ build tools, and that should only be required if you install the -msvc toolchain. MSVCR120.dll should not be required unless you explicitly chose "additional download options" and downloaded the -msvc version of rustup itself, which is currently not recommended, and provides no additional benefits.

**Comment by mark-summerfield** [comment]
I'm sorry but I can't remember now.

**Comment by stacktracer** [comment]
I, too, get the "missing MSVCR120.dll" error when running rustup-init.exe. I am definitely using the -gnu build of rustup-init.exe.

However, the error only pops up at the tail end of rustup-init -- rustc, rust-std, and cargo get successfully installed before the error.

It seems like rustup-init, at the very end, is trying to run "rustc --version" (so that it can print a success message), and that attempt to launch rustc is what triggers the error dialog.

**Comment by Diggsey** [comment]
It sounds like rustc itself may have an unexpected dependency on the MSVCRT which is not satisfied by the VC++ build tools?

@retep998 Do you know if this is the case? If so we can add whatever other dependencies rustc has to the instructions at install time.

**Comment by retep998** [comment]
I'm pretty sure the latest rustup rustc and cargo all statically link the CRT now so there shouldn't be any dependencies on VC++ redistributables.

**Comment by Diggsey** [comment]
@retep998 Thanks!

Please reopen if the issue re-occurs.

**Comment by mark-summerfield** [comment]
Rust 1.17.0 doesn't seem to have improved the Windows user installation experience. I downloaded and ran the rustup-init.exe and it gave me a console with a big red warning that I needed to install C++ build tools before proceeding. For me one of the whole points of using Rust is so I don't depend on the C/C++ ecosystem. Anyway, it gave a link to the needed build tools and I got their installer and that didn't work saying I needed .Net 4.5.1 or some such and I decided not to go round that loop again. (I do have Mingw64 installed but have no idea how to tell the Rust installer about it. I tried the 'custom' install option but when it asked for the 'default host triple' I could guess it wanted x86_64-pc-windows- but not what the end should be, so once again I've given up for now. Windows users generally expect things to just work: compare with Go's installer which is easy and fast and works.
