### ISSUE TITLE
Auto commands to automatically install crates after un update

### ISSUE THREAD

**Issue by antoyo** [rust-lang/rustup#974]
Hello.
One issue that is annoying is that we [need to reinstall clippy when updating to a newer nightly](https://github.com/Manishearth/rust-clippy/issues/937).
It would be nice if rustup supported some form of (perhaps limited) auto command so that we can reinstall clippy when running `rustup update`.
Thanks to add this feature.

**Comment by brson** [comment]
The current plan is to solve this by distributing clippy with rustup instead of cargo.

I do not yet know of a portable solution for making crates that dynamically link to std work correctly with rustup, though `rustup run` exists for this purpose, to set up the environment properly for dynamic loading.

Programs like clippy are intrinsically tied to the compiler internals, so just switching between toolchains, let alone upgrading, will break them.
